const APP_DATA = {
  stages: [
    { id: 'new', name: 'Новые', color: '#818cf8' },
    { id: 'qual', name: 'Квалификация', color: '#00cec9' },
    { id: 'nego', name: 'Переговоры', color: '#f59e0b' },
    { id: 'contract', name: 'Договор', color: '#a855f7' },
    { id: 'won', name: 'Выиграно', color: '#34d399' },
  ],

  deals: [
    { id: 1, company: 'Ромашка ООО', amount: 5400000, stage: 'nego', owner: 'Анна Ковалёва', prob: 72, contact: 'Игорь Смирнов', phone: '+7 916 234-11-22', city: 'Москва', industry: 'Ритейл' },
    { id: 2, company: 'ТехноСфера', amount: 2100000, stage: 'qual', owner: 'Дмитрий Орлов', prob: 45, contact: 'Мария Петрова', phone: '+7 903 555-01-09', city: 'Санкт-Петербург', industry: 'IT' },
    { id: 3, company: 'ГринЛайт', amount: 8900000, stage: 'contract', owner: 'Анна Ковалёва', prob: 88, contact: 'Олег Кузнецов', phone: '+7 921 777-33-44', city: 'Москва', industry: 'Энергетика' },
    { id: 4, company: 'Вектор Групп', amount: 1200000, stage: 'new', owner: 'Елена Соколова', prob: 20, contact: 'Павел Новиков', phone: '+7 985 100-20-30', city: 'Казань', industry: 'Логистика' },
    { id: 5, company: 'АкваСтрой', amount: 6700000, stage: 'nego', owner: 'Дмитрий Орлов', prob: 58, contact: 'Наталья Волкова', phone: '+7 926 848-77-11', city: 'Москва', industry: 'Строительство' },
    { id: 6, company: 'МедиаПлюс', amount: 3300000, stage: 'won', owner: 'Елена Соколова', prob: 100, contact: 'Сергей Лебедев', phone: '+7 917 222-88-99', city: 'Екатеринбург', industry: 'Медиа' },
    { id: 7, company: 'Финмакс', amount: 14500000, stage: 'new', owner: 'Анна Ковалёва', prob: 30, contact: 'Виктор Соловьёв', phone: '+7 999 004-55-66', city: 'Москва', industry: 'Финансы' },
    { id: 8, company: 'БиоФарм', amount: 4200000, stage: 'qual', owner: 'Елена Соколова', prob: 50, contact: 'Ирина Морозова', phone: '+7 963 321-45-67', city: 'Новосибирск', industry: 'Фарма' },
  ],

  tasks: [
    { id: 1, name: 'Отправить КП компании «Ромашка»', sub: 'Сделка · Ромашка ООО · до 16:00', priority: 'high', icon: 'fa-fire', iconBg: 'rgba(239,68,68,.18)', iconColor: '#f87171', status: 'work', done: false },
    { id: 2, name: 'Согласовать договор с юристом', sub: 'Сделка · ГринЛайт · на согласовании', priority: 'medium', icon: 'fa-file-signature', iconBg: 'rgba(245,158,11,.18)', iconColor: '#fbbf24', status: 'review', done: false },
    { id: 3, name: 'Позвонить клиенту «ТехноСфера»', sub: 'Уточнить бюджет проекта · сегодня', priority: 'medium', icon: 'fa-phone', iconBg: 'rgba(99,102,241,.18)', iconColor: '#818cf8', status: 'work', done: false },
    { id: 4, name: 'Подготовить презентацию для «Финмакс»', sub: 'Сделка · Финмакс · завтра', priority: 'low', icon: 'fa-file-lines', iconBg: 'rgba(52,211,153,.18)', iconColor: '#34d399', status: 'work', done: false },
    { id: 5, name: 'Выставить счёт «МедиаПлюс»', sub: 'Сделка закрыта · выполнено', priority: 'low', icon: 'fa-circle-check', iconBg: 'rgba(52,211,153,.18)', iconColor: '#34d399', status: 'done', done: true },
    { id: 6, name: 'Провести демо продукта «Вектор Групп»', sub: 'Встреча · четверг 14:00', priority: 'medium', icon: 'fa-video', iconBg: 'rgba(99,102,241,.18)', iconColor: '#818cf8', status: 'work', done: false },
    { id: 7, name: 'Обновить контактные данные «АкваСтрой»', sub: 'Мастер чистоты данных · выполнено', priority: 'low', icon: 'fa-circle-check', iconBg: 'rgba(52,211,153,.18)', iconColor: '#34d399', status: 'done', done: true },
  ],

  team: [
    { name: 'Анна Ковалёва', role: 'Руководитель отдела', status: 'online', deals: 3, calls: 47, tasks: 8 },
    { name: 'Дмитрий Орлов', role: 'Менеджер продаж', status: 'online', deals: 2, calls: 38, tasks: 5 },
    { name: 'Елена Соколова', role: 'Менеджер продаж', status: 'meeting', deals: 3, calls: 41, tasks: 6 },
    { name: 'Пётр Васильев', role: 'CEO', status: 'online', deals: 0, calls: 12, tasks: 3 },
    { name: 'Ольга Зайцева', role: 'Маркетинг', status: 'offline', deals: 0, calls: 9, tasks: 4 },
    { name: 'Максим Титов', role: 'Юрист', status: 'away', deals: 0, calls: 5, tasks: 7 },
  ],

  feedItems: [
    {
      group: 'Сегодня',
      type: 'deal',
      icon: 'fa-handshake',
      iconBg: 'rgba(52,211,153,.18)',
      iconColor: '#34d399',
      tag: '72%',
      tagBg: 'rgba(52,211,153,.2)',
      tagColor: '#34d399',
      title: 'Ромашка ООО — Сделка · Переговоры · 5 400 000 ₽',
      desc: 'Следующее действие: обсудить условия оплаты. Клиент проявил высокий интерес после демонстрации продукта.',
      actions: [
        { label: 'Позвонить', primary: true, action: 'call:Ромашка ООО' },
        { label: 'Написать', primary: false, action: 'toast:Открыт чат со сделкой' },
      ],
    },
    {
      group: 'Сегодня',
      type: 'task',
      icon: 'fa-list-check',
      iconBg: 'rgba(99,102,241,.18)',
      iconColor: '#818cf8',
      tag: 'Срочно',
      tagBg: 'rgba(248,113,113,.2)',
      tagColor: '#f87171',
      title: 'Отправить КП компании «Ромашка»',
      desc: 'Задача · срок до 16:00. Подготовлен черновик коммерческого предложения на основе истории переписки.',
      actions: [
        { label: 'Выполнить', primary: true, action: 'toast:Задача выполнена' },
        { label: 'Делегировать', primary: false, action: 'toast:Задача делегирована' },
      ],
    },
    {
      group: 'Сегодня',
      type: 'notif',
      icon: 'fa-envelope-open',
      iconBg: 'rgba(251,191,36,.18)',
      iconColor: '#fbbf24',
      tag: 'Прочитано',
      tagBg: 'rgba(251,191,36,.2)',
      tagColor: '#fbbf24',
      title: 'Клиент прочитал ваше письмо',
      desc: 'Уведомление · ГринЛайт · 08:47. Олег Кузнецов открыл письмо с договором и провёл на нём 4 минуты. Хороший знак для закрытия сделки.',
      actions: [
        { label: 'Открыть сделку', primary: true, action: 'deal:3' },
      ],
    },
    {
      group: 'Сегодня',
      type: 'task',
      icon: 'fa-phone',
      iconBg: 'rgba(99,102,241,.18)',
      iconColor: '#818cf8',
      tag: 'В работе',
      tagBg: 'rgba(99,102,241,.2)',
      tagColor: '#818cf8',
      title: 'Позвонить клиенту «ТехноСфера»',
      desc: 'Задача · уточнить бюджет проекта · сегодня до 17:00',
      actions: [
        { label: 'Позвонить', primary: true, action: 'call:ТехноСфера' },
        { label: 'Перенести', primary: false, action: 'toast:Задача перенесена на завтра' },
      ],
    },
    {
      group: 'Вчера',
      type: 'deal',
      icon: 'fa-handshake',
      iconBg: 'rgba(168,85,247,.18)',
      iconColor: '#c084fc',
      tag: '88%',
      tagBg: 'rgba(52,211,153,.2)',
      tagColor: '#34d399',
      title: 'ГринЛайт — Сделка · Договор · 8 900 000 ₽',
      desc: 'Договор отправлен на согласование. Клиент связался для уточнения технических деталей.',
      actions: [
        { label: 'Открыть сделку', primary: true, action: 'deal:3' },
      ],
    },
    {
      group: 'Вчера',
      type: 'notif',
      icon: 'fa-triangle-exclamation',
      iconBg: 'rgba(248,113,113,.18)',
      iconColor: '#f87171',
      tag: 'Внимание',
      tagBg: 'rgba(248,113,113,.2)',
      tagColor: '#f87171',
      title: 'Риск оттока: 2 клиента',
      desc: 'Предиктивный скоринг · У клиентов «Вектор Групп» и «Финмакс» снизилась активность. Рекомендую персональное касание в течение 48 часов.',
      actions: [
        { label: 'Показать план', primary: true, action: 'toast:Сформирован план удержания' },
      ],
    },
    {
      group: 'Вчера',
      type: 'event',
      icon: 'fa-video',
      iconBg: 'rgba(99,102,241,.18)',
      iconColor: '#818cf8',
      tag: 'Запись',
      tagBg: 'rgba(99,102,241,.2)',
      tagColor: '#818cf8',
      title: 'Встреча: демо для «АкваСтрой»',
      desc: 'Стенограмма готова. Выделены ключевые договорённости и созданы 2 задачи автоматически.',
      actions: [
        { label: 'Смотреть запись', primary: false, action: 'toast:Открыта запись встречи' },
      ],
    },
    {
      group: 'Вчера',
      type: 'msg',
      icon: 'fa-comment-dots',
      iconBg: 'rgba(99,102,241,.18)',
      iconColor: '#818cf8',
      tag: 'Чат',
      tagBg: 'rgba(99,102,241,.2)',
      tagColor: '#818cf8',
      title: 'Дмитрий Орлов — Чат · Запуск нового продукта',
      desc: '«Коллеги, выложил новые макеты в рабочее пространство. Нужна проверка до пятницы.»',
      actions: [
        { label: 'Ответить', primary: true, action: 'toast:Ответ отправлен' },
        { label: 'В задачу', primary: false, action: 'toast:Создана задача из сообщения' },
      ],
    },
    {
      group: 'Вчера',
      type: 'deal',
      icon: 'fa-handshake',
      iconBg: 'rgba(52,211,153,.18)',
      iconColor: '#34d399',
      tag: '100%',
      tagBg: 'rgba(52,211,153,.2)',
      tagColor: '#34d399',
      title: 'МедиаПлюс — Сделка закрыта · 3 300 000 ₽',
      desc: 'Счёт выставлен и оплачен. Клиент доволен. Попросил оставить отзыв.',
      actions: [
        { label: 'Открыть сделку', primary: true, action: 'deal:6' },
        { label: 'Попросить отзыв', primary: false, action: 'toast:Запрос на отзыв отправлен' },
      ],
    },
    {
      group: 'На прошлой неделе',
      type: 'notif',
      icon: 'fa-star',
      iconBg: 'rgba(251,191,36,.18)',
      iconColor: '#fbbf24',
      tag: 'Достижение',
      tagBg: 'rgba(251,191,36,.2)',
      tagColor: '#fbbf24',
      title: 'Вы перевысили план по звонкам на 20%',
      desc: 'Виртуальная медаль «Золотой звонок» присвоена. Бонус за квартал увеличен.',
      actions: [],
    },
  ],

  calendarEvents: {
    5: [{ t: 'Демо · Вектор', c: '#6366f1' }],
    10: [{ t: 'Звонок · Ромашка', c: '#34d399' }, { t: 'Встреча CEO', c: '#fbbf24' }],
    14: [{ t: 'Демо · АкваСтрой', c: '#818cf8' }],
    18: [{ t: 'Подписание', c: '#a855f7' }],
    22: [{ t: 'Ретро', c: '#fbbf24' }],
    27: [{ t: 'Дедлайн КП', c: '#f87171' }],
  },

  analytics: {
    stats: [
      { icon: 'fa-sack-dollar', color: '#34d399', value: '46.3М', label: 'Сумма сделок', trend: '+12.4% за месяц', trendUp: true },
      { icon: 'fa-handshake', color: '#818cf8', value: '8', label: 'Активных сделок', trend: '+2 новых', trendUp: true },
      { icon: 'fa-bullseye', color: '#fbbf24', value: '85%', label: 'Выполнение плана', trend: 'До цели 15%', trendUp: false },
      { icon: 'fa-percent', color: '#818cf8', value: '28%', label: 'Конверсия', trend: '+3.1% за месяц', trendUp: true },
    ],
    bars: [
      { m: 'Май', v: 60 },
      { m: 'Июн', v: 75 },
      { m: 'Июл', v: 55 },
      { m: 'Авг', v: 85 },
      { m: 'Сен', v: 70 },
      { m: 'Окт', v: 92 },
    ],
    funnel: [
      { n: 'Лиды', v: 100, c: '#818cf8', cnt: 120 },
      { n: 'Квалификация', v: 72, c: '#00cec9', cnt: 86 },
      { n: 'Переговоры', v: 48, c: '#f59e0b', cnt: 58 },
      { n: 'Договор', v: 30, c: '#a855f7', cnt: 36 },
      { n: 'Закрыто', v: 22, c: '#34d399', cnt: 26 },
    ],
  },

  comms: [
    { icon: 'fa-video', color: '#818cf8', title: 'Видеозвонок', desc: 'WebRTC HD · до 100 участников' },
    { icon: 'fa-comment-dots', color: '#34d399', title: 'Корп. чат', desc: 'Контекстные чаты по сделкам' },
    { icon: 'fa-envelope', color: '#f472b6', title: 'Email', desc: 'Шаблоны · трекинг открытий' },
    { icon: 'fa-phone-volume', color: '#fbbf24', title: 'Телефония', desc: 'SIP · запись · расшифровка' },
    { icon: 'fa-headset', color: '#a855f7', title: 'Поддержка', desc: 'Тикеты · база знаний · SLA' },
  ],

  settings: [
    { icon: 'fa-shield-halved', color: '#34d399', bg: 'rgba(52,211,153,.18)', title: 'Двухфакторная аутентификация', desc: 'TOTP + Push · Активна для всех пользователей' },
    { icon: 'fa-users-gear', color: '#818cf8', bg: 'rgba(99,102,241,.18)', title: 'Роли и права (RBAC)', desc: '6 ролей · Field-level security · Маскировка данных' },
    { icon: 'fa-plug-circle-bolt', color: '#fbbf24', bg: 'rgba(245,158,11,.18)', title: 'Интеграции · Marketplace', desc: '1С, Jira, Google Workspace, ЮKassa подключены' },
    { icon: 'fa-lock', color: '#f87171', bg: 'rgba(248,113,113,.18)', title: 'Шифрование данных', desc: 'AES-256 · Шифрование в покое и при передаче' },
    { icon: 'fa-clock-rotate-left', color: '#a855f7', bg: 'rgba(168,85,247,.18)', title: 'Аудит и логирование', desc: 'Полный аудит действий · Хранение 3 года' },
  ],
};
