const APP_DATA = {
  stages: [
    { id: 'new', name: 'Новые', color: '#818cf8' },
    { id: 'qual', name: 'Квалификация', color: '#00cec9' },
    { id: 'nego', name: 'Переговоры', color: '#f59e0b' },
    { id: 'contract', name: 'Договор', color: '#a855f7' },
    { id: 'won', name: 'Выиграно', color: '#34d399' },
  ],

  deals: [
    { id: 1, company: 'Ромашка ООО', amount: 5400000, stage: 'nego', owner: 'Анна Ковалёва', prob: 72, contact: 'Игорь Смирнов', phone: '+7 916 234-11-22', city: 'Москва', industry: 'Ритейл', type: 'company' },
    { id: 2, company: 'ТехноСфера', amount: 2100000, stage: 'qual', owner: 'Дмитрий Орлов', prob: 45, contact: 'Мария Петрова', phone: '+7 903 555-01-09', city: 'Санкт-Петербург', industry: 'IT', type: 'company' },
    { id: 3, company: 'ГринЛайт', amount: 8900000, stage: 'contract', owner: 'Анна Ковалёва', prob: 88, contact: 'Олег Кузнецов', phone: '+7 921 777-33-44', city: 'Москва', industry: 'Энергетика', type: 'company' },
    { id: 4, company: 'Вектор Групп', amount: 1200000, stage: 'new', owner: 'Елена Соколова', prob: 20, contact: 'Павел Новиков', phone: '+7 985 100-20-30', city: 'Казань', industry: 'Логистика', type: 'contact', contactIdx: 8 },
    { id: 5, company: 'АкваСтрой', amount: 6700000, stage: 'nego', owner: 'Дмитрий Орлов', prob: 58, contact: 'Наталья Волкова', phone: '+7 926 848-77-11', city: 'Москва', industry: 'Строительство', type: 'company' },
    { id: 6, company: 'МедиаПлюс', amount: 3300000, stage: 'won', owner: 'Елена Соколова', prob: 100, contact: 'Сергей Лебедев', phone: '+7 917 222-88-99', city: 'Екатеринбург', industry: 'Медиа', type: 'company' },
    { id: 7, company: 'Финмакс', amount: 14500000, stage: 'new', owner: 'Анна Ковалёва', prob: 30, contact: 'Виктор Соловьёв', phone: '+7 999 004-55-66', city: 'Москва', industry: 'Финансы', type: 'company' },
    { id: 8, company: 'БиоФарм', amount: 4200000, stage: 'qual', owner: 'Елена Соколова', prob: 50, contact: 'Ирина Морозова', phone: '+7 963 321-45-67', city: 'Новосибирск', industry: 'Фарма', type: 'company' },
  ],

  tasks: [],

  team: [
    { name: 'Анна Ковалёва', role: 'Руководитель отдела', status: 'online', deals: 3, calls: 47, tasks: 8 },
    { name: 'Дмитрий Орлов', role: 'Менеджер продаж', status: 'online', deals: 2, calls: 38, tasks: 5 },
    { name: 'Елена Соколова', role: 'Менеджер продаж', status: 'meeting', deals: 3, calls: 41, tasks: 6 },
    { name: 'Пётр Васильев', role: 'CEO', status: 'online', deals: 0, calls: 12, tasks: 3 },
    { name: 'Ольга Зайцева', role: 'Маркетинг', status: 'offline', deals: 0, calls: 9, tasks: 4 },
    { name: 'Максим Титов', role: 'Юрист', status: 'away', deals: 0, calls: 5, tasks: 7 },
  ],

  feedItems: [
    {
      group: 'Сегодня',
      type: 'deal',
      icon: 'fa-handshake',
      iconBg: 'rgba(52,211,153,.18)',
      iconColor: '#34d399',
      tag: '72%',
      tagBg: 'rgba(52,211,153,.35)',
      tagColor: '#34d399',
      title: 'Ромашка ООО — Сделка · Переговоры · 5 400 000 ₽',
      desc: 'Следующее действие: обсудить условия оплаты. Клиент проявил высокий интерес после демонстрации продукта.',
      actions: [
        { label: 'Позвонить', primary: true, action: 'call:Ромашка ООО' },
        { label: 'Написать', primary: false, action: 'toast:Открыт чат со сделкой' },
      ],
    },
    {
      group: 'Сегодня',
      type: 'task',
      icon: 'fa-list-check',
      iconBg: 'rgba(99,102,241,.18)',
      iconColor: '#818cf8',
      tag: 'Срочно',
      tagBg: 'rgba(248,113,113,.35)',
      tagColor: '#f87171',
      title: 'Отправить КП компании «Ромашка»',
      desc: 'Задача · срок до 16:00. Подготовлен черновик коммерческого предложения на основе истории переписки.',
      actions: [
        { label: 'Выполнить', primary: true, action: 'toast:Задача выполнена' },
        { label: 'Делегировать', primary: false, action: 'toast:Задача делегирована' },
      ],
    },
    {
      group: 'Сегодня',
      type: 'notif',
      icon: 'fa-envelope-open',
      iconBg: 'rgba(251,191,36,.18)',
      iconColor: '#fbbf24',
      tag: 'Прочитано',
      tagBg: 'rgba(251,191,36,.35)',
      tagColor: '#fbbf24',
      title: 'Клиент прочитал ваше письмо',
      desc: 'Уведомление · ГринЛайт · 08:47. Олег Кузнецов открыл письмо с договором и провёл на нём 4 минуты. Хороший знак для закрытия сделки.',
      actions: [
        { label: 'Открыть сделку', primary: true, action: 'deal:3' },
      ],
    },
    {
      group: 'Сегодня',
      type: 'task',
      icon: 'fa-phone',
      iconBg: 'rgba(99,102,241,.18)',
      iconColor: '#818cf8',
      tag: 'В работе',
      tagBg: 'rgba(99,102,241,.35)',
      tagColor: '#818cf8',
      title: 'Позвонить клиенту «ТехноСфера»',
      desc: 'Задача · уточнить бюджет проекта · сегодня до 17:00',
      actions: [
        { label: 'Позвонить', primary: true, action: 'call:ТехноСфера' },
        { label: 'Перенести', primary: false, action: 'toast:Задача перенесена на завтра' },
      ],
    },
    {
      group: 'Вчера',
      type: 'deal',
      icon: 'fa-handshake',
      iconBg: 'rgba(168,85,247,.18)',
      iconColor: '#c084fc',
      tag: '88%',
      tagBg: 'rgba(52,211,153,.35)',
      tagColor: '#34d399',
      title: 'ГринЛайт — Сделка · Договор · 8 900 000 ₽',
      desc: 'Договор отправлен на согласование. Клиент связался для уточнения технических деталей.',
      actions: [
        { label: 'Открыть сделку', primary: true, action: 'deal:3' },
      ],
    },
    {
      group: 'Вчера',
      type: 'notif',
      icon: 'fa-triangle-exclamation',
      iconBg: 'rgba(248,113,113,.18)',
      iconColor: '#f87171',
      tag: 'Внимание',
      tagBg: 'rgba(248,113,113,.35)',
      tagColor: '#f87171',
      title: 'Риск оттока: 2 клиента',
      desc: 'Предиктивный скоринг · У клиентов «Вектор Групп» и «Финмакс» снизилась активность. Рекомендую персональное касание в течение 48 часов.',
      actions: [
        { label: 'Показать план', primary: true, action: 'toast:Сформирован план удержания' },
      ],
    },
    {
      group: 'Вчера',
      type: 'event',
      icon: 'fa-video',
      iconBg: 'rgba(99,102,241,.18)',
      iconColor: '#818cf8',
      tag: 'Запись',
      tagBg: 'rgba(99,102,241,.35)',
      tagColor: '#818cf8',
      title: 'Встреча: демо для «АкваСтрой»',
      desc: 'Стенограмма готова. Выделены ключевые договорённости и созданы 2 задачи автоматически.',
      actions: [
        { label: 'Смотреть запись', primary: false, action: 'toast:Открыта запись встречи' },
      ],
    },
    {
      group: 'Вчера',
      type: 'msg',
      icon: 'fa-comment-dots',
      iconBg: 'rgba(99,102,241,.18)',
      iconColor: '#818cf8',
      tag: 'Чат',
      tagBg: 'rgba(99,102,241,.35)',
      tagColor: '#818cf8',
      title: 'Дмитрий Орлов — Чат · Запуск нового продукта',
      desc: '«Коллеги, выложил новые макеты в рабочее пространство. Нужна проверка до пятницы.»',
      actions: [
        { label: 'Ответить', primary: true, action: 'toast:Ответ отправлен' },
        { label: 'В задачу', primary: false, action: 'toast:Создана задача из сообщения' },
      ],
    },
    {
      group: 'Вчера',
      type: 'deal',
      icon: 'fa-handshake',
      iconBg: 'rgba(52,211,153,.18)',
      iconColor: '#34d399',
      tag: '100%',
      tagBg: 'rgba(52,211,153,.35)',
      tagColor: '#34d399',
      title: 'МедиаПлюс — Сделка закрыта · 3 300 000 ₽',
      desc: 'Счёт выставлен и оплачен. Клиент доволен. Попросил оставить отзыв.',
      actions: [
        { label: 'Открыть сделку', primary: true, action: 'deal:6' },
        { label: 'Попросить отзыв', primary: false, action: 'toast:Запрос на отзыв отправлен' },
      ],
    },
    {
      group: 'На прошлой неделе',
      type: 'notif',
      icon: 'fa-star',
      iconBg: 'rgba(251,191,36,.18)',
      iconColor: '#fbbf24',
      tag: 'Достижение',
      tagBg: 'rgba(251,191,36,.35)',
      tagColor: '#fbbf24',
      title: 'Вы перевысили план по звонкам на 20%',
      desc: 'Виртуальная медаль «Золотой звонок» присвоена. Бонус за квартал увеличен.',
      actions: [],
    },
  ],

  calendarEvents: {
    5: [{ t: 'Демо · Вектор', c: '#6366f1' }],
    10: [{ t: 'Звонок · Ромашка', c: '#34d399' }, { t: 'Встреча CEO', c: '#fbbf24' }],
    14: [{ t: 'Демо · АкваСтрой', c: '#818cf8' }],
    18: [{ t: 'Подписание', c: '#a855f7' }],
    22: [{ t: 'Ретро', c: '#fbbf24' }],
    27: [{ t: 'Дедлайн КП', c: '#f87171' }],
  },

  analytics: {
    stats: [
      { icon: 'fa-handshake', color: '#818cf8', value: '8', label: 'Активных сделок', trend: '+2 новых', trendUp: true },
      { icon: 'fa-percent', color: '#818cf8', value: '28%', label: 'Конверсия', trend: '+3.1% за месяц', trendUp: true },
    ],
    bars: [
      { m: 'Май', v: 60 },
      { m: 'Июн', v: 75 },
      { m: 'Июл', v: 55 },
      { m: 'Авг', v: 85 },
      { m: 'Сен', v: 70 },
      { m: 'Окт', v: 92 },
    ],
  },

  funnel: [
    { n: 'Лиды', v: 100, c: '#818cf8', cnt: 120 },
    { n: 'Квалификация', v: 72, c: '#00cec9', cnt: 86 },
    { n: 'Переговоры', v: 48, c: '#f59e0b', cnt: 58 },
    { n: 'Договор', v: 30, c: '#a855f7', cnt: 36 },
    { n: 'Закрыто', v: 22, c: '#34d399', cnt: 26 },
  ],

  comms: [
    { icon: 'fa-video', color: '#818cf8', title: 'Видеовстречи', desc: 'WebRTC · запись · резюме встреч' },
    { icon: 'fa-comment-dots', color: '#34d399', title: 'Корп. чат', desc: 'Контекстные чаты по сделкам' },
    { icon: 'fa-envelope', color: '#f472b6', title: 'Корпоративная почта', desc: 'Инбокс · CRM-контекст · шаблоны ответов' },
    { icon: 'fa-phone-volume', color: '#fbbf24', title: 'Телефония', desc: 'SIP · запись · расшифровка' },
    { icon: 'fa-headset', color: '#a855f7', title: 'Поддержка', desc: 'Тикеты · база знаний · SLA' },
  ],

  settings: [
    { icon: 'fa-shield-halved', color: '#34d399', bg: 'rgba(52,211,153,.18)', title: 'Двухфакторная аутентификация', desc: 'TOTP + Push · Активна для всех пользователей' },
    { icon: 'fa-users-gear', color: '#818cf8', bg: 'rgba(99,102,241,.18)', title: 'Роли и права (RBAC)', desc: '6 ролей · Field-level security · Маскировка данных' },
    { icon: 'fa-plug-circle-bolt', color: '#fbbf24', bg: 'rgba(245,158,11,.18)', title: 'Интеграции · Marketplace', desc: '1С, Jira, Google Workspace, ЮKassa подключены' },
    { icon: 'fa-lock', color: '#f87171', bg: 'rgba(248,113,113,.18)', title: 'Шифрование данных', desc: 'AES-256 · Шифрование в покое и при передаче' },
    { icon: 'fa-clock-rotate-left', color: '#a855f7', bg: 'rgba(168,85,247,.18)', title: 'Аудит и логирование', desc: 'Полный аудит действий · Хранение 3 года' },
  ],

  companies: [
    { n: 'ЭЛВЕНТ ПЛЮС, ООО', inn: '7716894440', c: 'linear-gradient(135deg,#6366f1,#a855f7)', deal: '14.09.2026 14:00', date: '01.12.2025', resp: 'Анна Ковалёва', path: '',
      industry: 'Оптовая торговля', city: 'Москва', employees: 120, rating: 4.8, clientSince: 2019, revenue: '≈ 340 млн ₽',
      phone: '+7 905 648-04-65', email: 'info@elvent.ru', comments: [],
      contacts: [
        { name: 'Виктор Агафуров', role: 'Ген. директор', tag: 'ЛПР', av: 'ВА' },
        { name: 'Ирина Ковалёва', role: 'Снабжение', tag: 'закупки', av: 'ИК' },
        { name: 'Сергей Петров', role: 'Гл. инженер', tag: 'техспец', av: 'СП' },
      ],
      related: [
        { name: 'ЭЛВЕНТ ГРУПП, АО', type: 'Материнская компания', icon: 'fa-building' },
        { name: 'ТехСнаб, ООО', type: 'Партнёр', icon: 'fa-handshake' },
      ],
      source: 'Рекомендация клиента',
      tags: ['VIP', 'Опт', 'Москва'],
      totalRevenue: '18,4 млн ₽', totalDeals: 14, avgCheck: '1,3 млн ₽',
      desc: 'ООО «ЭЛВЕНТ ПЛЮС» — оптовый поставщик электротехнического оборудования на московском рынке с 2011 года. Ключевой аккаунт с высокой лояльностью, регулярные закупки.',
      insights: [
        { type: 'red', icon: 'fa-triangle-exclamation', title: 'Риск оттока — 64%', desc: 'Активность снизилась на 40% за последний месяц. Рекомендуем инициировать контакт с ЛПР.', btn: 'Создать задачу на удержание', risk: 64 },
        { type: 'green', icon: 'fa-arrow-trend-up', title: 'Апсейл-возможность', desc: 'Клиент не использует линейку «Автоматизация». Потенциал апсейла ≈ 2,1 млн ₽ в год.', btn: 'Отправить КП' },
        { type: 'blue', icon: 'fa-lightbulb', title: 'Следующее лучшее действие', desc: 'Позвонить Виктору Агафурову завтра в 10:00 — вероятность закрытия текущей сделки 78%.' },
        { type: 'yellow', icon: 'fa-clock-rotate-left', title: 'Контракт истекает через 24 дня', desc: 'Договор №2024-118 требует продления до 30 октября.', btn: 'Продлить контракт' },
      ],
      dealsList: [
        { name: 'Поставка оборудования Q4', sub: 'Открыта 12.09 · Данияр Сабитов', stage: 'Переговоры', stageClass: 'b-blue', sum: '2 400 000 ₽' },
        { name: 'Проект автоматизации склада', sub: 'Открыта 03.09 · Данияр Сабитов', stage: 'Согласование КП', stageClass: 'b-yellow', sum: '1 850 000 ₽' },
      ],
      dealsClosed: [
        { name: 'Годовой контракт 2024', sub: 'Закрыта 15.01', stage: 'Выиграна', stageClass: 'b-green', sum: '5 200 000 ₽' },
      ],
      commsHistory: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Исходящий звонок Виктору Агафурову', time: 'Сегодня 13:25 · 6 мин · есть расшифровка' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'Письмо: коммерческое предложение Q4', time: 'Вчера 16:40' },
        { icon: 'fa-video', cls: 'act-meet', text: 'Онлайн-встреча по проекту склада', time: '9 апреля 11:00 · 45 мин' },
      ],
      docs: [
        { name: 'Договор №2024-118', icon: 'fa-file-contract', meta: 'PDF · 240 КБ · 15.01.2024' },
        { name: 'КП «Поставка Q4»', icon: 'fa-file-invoice-dollar', meta: 'PDF · 180 КБ · 12.09.2024' },
        { name: 'Счёт №С-4412', icon: 'fa-receipt', meta: 'PDF · 95 КБ · 20.09.2024' },
      ],
      analytics: { q1: 45, q2: 70, q3: 55, q4: 85 },
      history: [
        { icon: 'fa-pen', cls: 'act-meet', text: 'Данияр Сабитов изменил статус на «Клиент»', time: 'Сегодня 09:14' },
        { icon: 'fa-plus', cls: 'act-call', text: 'Добавлен контакт «Мария Дроздова»', time: 'Вчера 15:20' },
        { icon: 'fa-robot', cls: 'act-mail', text: 'Робот обновил «Общую выручку»', time: '15.01 12:00' },
      ],
      nextSteps: [
        { icon: 'fa-phone', text: 'Позвонить Виктору завтра в 10:00' },
        { icon: 'fa-paper-plane', text: 'Отправить КП по линейке «Автоматизация»' },
      ],
      tasks: [
        { text: 'Связаться с клиентом', due: 'Просрочено · 14 сентября', overdue: true },
        { text: 'Согласовать спецификацию Q4', due: 'До 15 октября', overdue: false },
        { text: 'Продлить договор №2024-118', due: 'До 30 октября', overdue: false },
      ],
      activities: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Виктору Агафурову', time: 'Сегодня 13:25' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'Письмо: КП Q4', time: 'Вчера 16:40' },
        { icon: 'fa-video', cls: 'act-meet', text: 'Встреча по складу', time: '9 апреля 11:00' },
      ],
    },
    { n: 'ООО "СТАНДАРТЭНЕРГО"', inn: '—', c: 'linear-gradient(135deg,#3b82f6,#6366f1)', deal: '27.08.2026 16:00', date: '15.05.2024', resp: 'Пётр Васильев', path: '',
      industry: 'Энергетика', city: 'Москва', employees: 85, rating: 4.5, clientSince: 2020, revenue: '≈ 210 млн ₽',
      phone: '+7 495 123-45-67', email: 'info@standartenergo.ru', comments: [],
      contacts: [
        { name: 'Алексей Морозов', role: 'Ген. директор', tag: 'ЛПР', av: 'АМ' },
        { name: 'Наталья Крылова', role: 'Закупки', tag: 'контракт', av: 'НК' },
        { name: 'Павел Егоров', role: 'Главный инженер', tag: 'техспец', av: 'ПЕ' },
      ],
      related: [{ name: 'Стандарт-Холдинг, АО', type: 'Материнская компания', icon: 'fa-building' }],
      source: 'Выставки', tags: ['Контракт', 'Энергетика', 'Москва'],
      totalRevenue: '8,2 млн ₽', totalDeals: 6, avgCheck: '1,4 млн ₽',
      desc: 'ООО "СТАНДАРТЭНЕРГО" — поставщик электроэнергетического оборудования на российском рынке. Специализируется на трансформаторах и распределительных устройствах. Работаем с 2020 года, стабильный рост закупок.',
      insights: [
        { type: 'green', icon: 'fa-arrow-trend-up', title: 'Растущий клиент', desc: 'Объём закупок вырос на 30% за полгода. Рекомендуем предложить расширенный сервисный контракт.', btn: 'Предложить сервис' },
        { type: 'blue', icon: 'fa-lightbulb', title: 'Кросс-продажа', desc: 'Клиент закупает только трансформаторы. Линейка «Автоматизация» может быть интересна для модернизации.', btn: 'Отправить КП' },
        { type: 'yellow', icon: 'fa-clock-rotate-left', title: 'Контракт истекает через 45 дней', desc: 'Договор №2023-087 требует продления. Подготовить предложение до конца августа.' },
      ],
      dealsList: [
        { name: 'Поставка трансформаторов ТМГ-250', sub: 'Открыта 27.08 · Пётр Васильев', stage: 'Переговоры', stageClass: 'b-blue', sum: '3 200 000 ₽' },
        { name: 'Модернизация подстанции', sub: 'Открыта 15.08 · Пётр Васильев', stage: 'Согласование КП', stageClass: 'b-yellow', sum: '1 800 000 ₽' },
      ],
      dealsClosed: [
        { name: 'Годовой контракт 2025', sub: 'Закрыта 10.01', stage: 'Выиграна', stageClass: 'b-green', sum: '4 100 000 ₽' },
      ],
      commsHistory: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Алексею Морозову — обсуждение условий', time: 'Вчера 14:00 · 12 мин' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'Письмо: КП по трансформаторам ТМГ', time: '25.08 10:30' },
        { icon: 'fa-video', cls: 'act-meet', text: 'Онлайн-встреча — презентация продукции', time: '20.08 11:00 · 35 мин' },
      ],
      contacts: [
        { name: 'Алексей Морозов', role: 'Ген. директор · +7 495 123-45-67', av: 'АМ' },
        { name: 'Наталья Крылова', role: 'Закупки · +7 495 123-45-68', av: 'НК' },
        { name: 'Павел Егоров', role: 'Главный инженер · +7 495 123-45-69', av: 'ПЕ' },
      ],
      docs: [
        { name: 'Договор №2023-087', icon: 'fa-file-contract', meta: 'PDF · 320 КБ · 15.01.2023' },
        { name: 'КП «Трансформаторы ТМГ»', icon: 'fa-file-invoice-dollar', meta: 'PDF · 210 КБ · 27.08.2026' },
        { name: 'Акт приёмки №045', icon: 'fa-receipt', meta: 'PDF · 85 КБ · 20.06.2026' },
      ],
      analytics: { q1: 30, q2: 50, q3: 40, q4: 65 },
      history: [
        { icon: 'fa-pen', cls: 'act-meet', text: 'Пётр Васильев обновил сумму сделки', time: 'Сегодня 09:30' },
        { icon: 'fa-plus', cls: 'act-call', text: 'Добавлен контакт «Павел Егоров»', time: '25.08 14:20' },
        { icon: 'fa-robot', cls: 'act-mail', text: 'Автоматическое обновление статуса', time: '20.08 12:00' },
      ],
      nextSteps: [
        { icon: 'fa-phone', text: 'Позвонить Алексею в понедельник в 10:00' },
        { icon: 'fa-paper-plane', text: 'Отправить обновлённое КП по модернизации' },
      ],
      tasks: [
        { text: 'Подготовить КП по модернизации', due: 'До 30 августа', overdue: false },
        { text: 'Согласовать условия с юристом', due: 'До 5 сентября', overdue: false },
        { text: 'Запросить ТУ у клиента', due: 'Просрочено · 20 августа', overdue: true },
      ],
      activities: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Алексею Морозову', time: 'Вчера 14:00' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'КП по трансформаторам', time: '25.08 10:30' },
        { icon: 'fa-video', cls: 'act-meet', text: 'Презентация продукции', time: '20.08 11:00' },
      ],
    },
    { n: 'ЭНЕРГОМАСТЕР, ООО', inn: '5014009147', c: 'linear-gradient(135deg,#f59e0b,#ef4444)', deal: '04.08.2026 16:00', date: '01.12.2025', resp: 'Дмитрий Орлов', path: '',
      industry: 'Строительство', city: 'Москва', employees: 200, rating: 4.2, clientSince: 2021, revenue: '≈ 520 млн ₽',
      phone: '+7 495 987-65-43', email: 'office@energomaster.ru', comments: [],
      contacts: [
        { name: 'Сергей Волков', role: 'Директор', tag: 'ЛПР', av: 'СВ' },
        { name: 'Ольга Петрова', role: 'Главный инженер', tag: 'ТЗ', av: 'ОП' },
        { name: 'Андрей Кузнецов', role: 'Снабжение', tag: 'закупки', av: 'АК' },
      ],
      related: [{ name: 'СтройМастер, ООО', type: 'Дочерняя компания', icon: 'fa-building' }, { name: 'ТехноСтрой, ООО', type: 'Партнёр', icon: 'fa-handshake' }],
      source: 'Холодные звонки', tags: ['Строительство', 'Промышленность', 'Крупный'],
      totalRevenue: '12,1 млн ₽', totalDeals: 8, avgCheck: '1,5 млн ₽',
      desc: 'ЭНЕРГОМАСТЕР — строительная компания, специализирующаяся на промышленных объектах. Выполняет полный цикл работ от проектирования до сдачи под ключ. Клиент с 2021 года.',
      insights: [
        { type: 'yellow', icon: 'fa-clock-rotate-left', title: 'Ожидает ответа — 3 дня', desc: 'КП отправлено 3 дня назад, ответа нет. Рекомендуем последующий звонок.', btn: 'Позвонить' },
        { type: 'red', icon: 'fa-triangle-exclamation', title: 'Снижение активности', desc: 'Клиент не заходил в портал 12 дней. Возможно, рассматривает конкурентов.', risk: 45 },
        { type: 'green', icon: 'fa-arrow-trend-up', title: 'Апсейл-потенциал', desc: 'Клиент расширяет производство. Потенциал апсейла ≈ 3,5 млн ₽.', btn: 'Подготовить предложение' },
      ],
      dealsList: [
        { name: 'Поставка оборудования Q4', sub: 'Открыта 04.08 · Дмитрий Орлов', stage: 'Переговоры', stageClass: 'b-blue', sum: '4 500 000 ₽' },
        { name: 'Проект автоматизации склада', sub: 'Открыта 01.08 · Дмитрий Орлов', stage: 'Согласование КП', stageClass: 'b-yellow', sum: '2 800 000 ₽' },
      ],
      dealsClosed: [
        { name: 'Годовой контракт 2025', sub: 'Закрыта 20.12', stage: 'Выиграна', stageClass: 'b-green', sum: '6 300 000 ₽' },
        { name: 'Поставка кабельной продукции', sub: 'Закрыта 15.06', stage: 'Выиграна', stageClass: 'b-green', sum: '3 100 000 ₽' },
      ],
      commsHistory: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Сергею Волкову — обсуждение сроков', time: 'Вчера 11:30 · 8 мин' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'Письмо: КП «Поставка оборудования Q4»', time: '04.08 09:15' },
        { icon: 'fa-phone', cls: 'act-call', text: 'Входящий звонок от Ольги Петровой', time: '01.08 16:40 · 22 мин' },
        { icon: 'fa-video', cls: 'act-meet', text: 'Совещание по проекту автоматизации', time: '28.07 10:00 · 1 час' },
      ],
      contacts: [
        { name: 'Сергей Волков', role: 'Директор · +7 495 987-65-43', av: 'СВ' },
        { name: 'Ольга Петрова', role: 'Главный инженер · +7 495 987-65-44', av: 'ОП' },
        { name: 'Андрей Кузнецов', role: 'Снабжение · +7 495 987-65-45', av: 'АК' },
      ],
      docs: [
        { name: 'Договор №2025-156', icon: 'fa-file-contract', meta: 'PDF · 420 КБ · 20.12.2025' },
        { name: 'КП «Оборудование Q4»', icon: 'fa-file-invoice-dollar', meta: 'PDF · 190 КБ · 04.08.2026' },
        { name: 'Счёт №С-7821', icon: 'fa-receipt', meta: 'PDF · 75 КБ · 01.08.2026' },
      ],
      analytics: { q1: 50, q2: 60, q3: 45, q4: 70 },
      history: [
        { icon: 'fa-pen', cls: 'act-meet', text: 'Дмитрий Орлов обновил статус сделки', time: '04.08 09:00' },
        { icon: 'fa-plus', cls: 'act-call', text: 'Добавлен контакт «Ольга Петрова»', time: '01.08 15:30' },
        { icon: 'fa-robot', cls: 'act-mail', text: 'Напоминание о просроченном КП', time: '01.08 10:00' },
      ],
      nextSteps: [
        { icon: 'fa-phone', text: 'Позвонить Сергею — уточнить по КП' },
        { icon: 'fa-paper-plane', text: 'Отправить напоминание о КП' },
      ],
      tasks: [
        { text: 'Подготовить КП по автоматизации', due: 'До 10 августа', overdue: true },
        { text: 'Согласовать спецификацию с Ольгой', due: 'До 15 августа', overdue: false },
        { text: 'Отправить счёт за июль', due: 'До 5 августа', overdue: true },
      ],
      activities: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Сергею Волкову', time: 'Вчера 11:30' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'КП «Оборудование Q4»', time: '04.08 09:15' },
        { icon: 'fa-video', cls: 'act-meet', text: 'Совещание по автоматизации', time: '28.07 10:00' },
      ],
    },
    { n: 'ООО "СТРОЙКОНТРАКТ"', inn: '2460056905', c: 'linear-gradient(135deg,#10b981,#059669)', deal: '04.08.2026 14:00', date: '18.09.2025', resp: 'Общие компании', path: 'Прочий трафик › Приложение',
      industry: 'Строительство', city: 'Краснодар', employees: 150, rating: 4.0, clientSince: 2022, revenue: '≈ 180 млн ₽',
      phone: '+7 861 234-56-78', email: 'info@stroykontakt.ru', comments: [],
      contacts: [
        { name: 'Игорь Петров', role: 'Руководитель', tag: 'ЛПР', av: 'ИП' },
        { name: 'Елена Смирнова', role: 'Закупки', tag: 'контракт', av: 'ЕС' },
      ],
      related: [{ name: 'КубаньСтрой, ООО', type: 'Партнёр', icon: 'fa-handshake' }],
      source: 'Прочий трафик', tags: ['Строительство', 'Юг', 'Средний бизнес'],
      totalRevenue: '4,5 млн ₽', totalDeals: 3, avgCheck: '1,5 млн ₽',
      desc: 'ООО "СТРОЙКОНТРАКТ" — строительная компания в Краснодаре, специализирующаяся на коммерческом строительстве. Активно развивает направление складской логистики.',
      insights: [
        { type: 'blue', icon: 'fa-lightbulb', title: 'Новый проект', desc: 'Клиент планирует строительство нового складского комплекса. Потенциал сделки ≈ 8 млн ₽.', btn: 'Назначить встречу' },
        { type: 'green', icon: 'fa-arrow-trend-up', title: 'Хорошая оплата', desc: 'Клиент всегда оплачивает вовремя. Рекомендуем предложить отсрочку для увеличения объёма.' },
      ],
      dealsList: [
        { name: 'Поставка стройматериалов', sub: 'Открыта 04.08 · Игорь Петров', stage: 'Квалификация', stageClass: 'b-blue', sum: '1 200 000 ₽' },
      ],
      dealsClosed: [
        { name: 'Поставка инструмента 2025', sub: 'Закрыта 10.03', stage: 'Выиграна', stageClass: 'b-green', sum: '2 800 000 ₽' },
      ],
      commsHistory: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Игорю Петрову — обсуждение нового проекта', time: '04.08 14:00 · 15 мин' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'Письмо: каталог продукции', time: '01.08 10:00' },
      ],
      contacts: [
        { name: 'Игорь Петров', role: 'Руководитель · +7 861 234-56-78', av: 'ИП' },
        { name: 'Елена Смирнова', role: 'Закупки · +7 861 234-56-79', av: 'ЕС' },
      ],
      docs: [
        { name: 'Договор №2022-034', icon: 'fa-file-contract', meta: 'PDF · 280 КБ · 18.09.2022' },
        { name: 'КП «Стройматериалы»', icon: 'fa-file-invoice-dollar', meta: 'PDF · 150 КБ · 04.08.2026' },
      ],
      analytics: { q1: 20, q2: 35, q3: 30, q4: 45 },
      history: [
        { icon: 'fa-plus', cls: 'act-call', text: 'Новая сделка «Поставка стройматериалов»', time: '04.08 14:00' },
        { icon: 'fa-robot', cls: 'act-mail', text: 'Автоматическое обновление контактов', time: '01.08 12:00' },
      ],
      nextSteps: [
        { icon: 'fa-phone', text: 'Позвонить Игорю — уточнить ТЗ на склад' },
        { icon: 'fa-paper-plane', text: 'Отправить каталог с актуальными ценами' },
      ],
      tasks: [
        { text: 'Подготовить ТКП на стройматериалы', due: 'До 12 августа', overdue: false },
        { text: 'Согласовать цены с отделом закупок', due: 'До 15 августа', overdue: false },
      ],
      activities: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Игорю Петрову', time: '04.08 14:00' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'Каталог продукции', time: '01.08 10:00' },
      ],
    },
    { n: 'ИНТЕРЛАЙН ИНЖИНИРИНГ, ООО', inn: '7805412169', c: 'linear-gradient(135deg,#8b5cf6,#a855f7)', deal: '03.08.2026 16:00', date: '01.12.2025', resp: 'Ольга Зайцева', path: '',
      industry: 'Инжиниринг', city: 'Санкт-Петербург', employees: 90, rating: 4.6, clientSince: 2020, revenue: '≈ 290 млн ₽',
      phone: '+7 812 345-67-89', email: 'info@interline-eng.ru', comments: [],
      contacts: [
        { name: 'Андрей Козлов', role: 'Тех. директор', tag: 'ЛПР', av: 'АК' },
        { name: 'Наталья Белова', role: 'Проектный менеджер', tag: 'проекты', av: 'НБ' },
        { name: 'Максим Орехов', role: 'Закупки', tag: 'контракт', av: 'МО' },
      ],
      related: [{ name: 'Инжиниринг-Центр, ООО', type: 'Дочерняя компания', icon: 'fa-building' }, { name: 'ПроектСтрой, АО', type: 'Стратегический партнёр', icon: 'fa-handshake' }],
      source: 'LinkedIn', tags: ['Инжиниринг', 'СПб', 'Проекты'],
      totalRevenue: '9,8 млн ₽', totalDeals: 5, avgCheck: '2,0 млн ₽',
      desc: 'ИНТЕРЛАЙН ИНЖИНИРИНГ — инжиниринговая компания в Санкт-Петербурге. Специализируется на проектировании инженерных систем для промышленных объектов. Высокий средний чек, стабильные закупки.',
      insights: [
        { type: 'blue', icon: 'fa-lightbulb', title: 'Потенциал роста', desc: 'Клиент расширяет штат на 25% и планирует новые проекты. Возможны крупные заказы на 5+ млн ₽.', btn: 'Назначить встречу' },
        { type: 'green', icon: 'fa-arrow-trend-up', title: 'Лояльный клиент', desc: 'NPS 9/10, 4 года сотрудничества. Рекомендуем программу лояльности.', btn: 'Предложить программу' },
        { type: 'yellow', icon: 'fa-clock-rotate-left', title: 'Дедлайн проекта — 15 дней', desc: 'Проект «Модернизация НПЗ» требует поставки оборудования до 20 августа.' },
      ],
      dealsList: [
        { name: 'Поставка для проекта «НПЗ»', sub: 'Открыта 03.08 · Ольга Зайцева', stage: 'Переговоры', stageClass: 'b-blue', sum: '5 200 000 ₽' },
        { name: 'Комплексная поставка Q4', sub: 'Открыта 01.08 · Ольга Зайцева', stage: 'Договор', stageClass: 'b-yellow', sum: '3 100 000 ₽' },
      ],
      dealsClosed: [
        { name: 'Проект «Автоматизация склада»', sub: 'Закрыта 15.05', stage: 'Выиграна', stageClass: 'b-green', sum: '4 800 000 ₽' },
        { name: 'Годовой контракт 2025', sub: 'Закрыта 10.01', stage: 'Выиграна', stageClass: 'b-green', sum: '6 200 000 ₽' },
      ],
      commsHistory: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Андрею Козлову — обсуждение ТЗ', time: '03.08 16:00 · 18 мин' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'Письмо: спецификация оборудования', time: '01.08 11:20' },
        { icon: 'fa-video', cls: 'act-meet', text: 'Техническая встреча — проект НПЗ', time: '28.07 14:00 · 1.5 часа' },
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Наталье Беловой — уточнение сроков', time: '25.07 10:00 · 10 мин' },
      ],
      contacts: [
        { name: 'Андрей Козлов', role: 'Тех. директор · +7 812 345-67-89', av: 'АК' },
        { name: 'Наталья Белова', role: 'Проектный менеджер · +7 812 345-67-90', av: 'НБ' },
        { name: 'Максим Орехов', role: 'Закупки · +7 812 345-67-91', av: 'МО' },
      ],
      docs: [
        { name: 'Договор №2020-012', icon: 'fa-file-contract', meta: 'PDF · 450 КБ · 01.12.2020' },
        { name: 'Спецификация «НПЗ»', icon: 'fa-file-lines', meta: 'PDF · 1.2 МБ · 01.08.2026' },
        { name: 'КП «Комплексная поставка Q4»', icon: 'fa-file-invoice-dollar', meta: 'PDF · 280 КБ · 01.08.2026' },
        { name: 'Акт приёмки №112', icon: 'fa-receipt', meta: 'PDF · 95 КБ · 15.05.2026' },
      ],
      analytics: { q1: 40, q2: 55, q3: 60, q4: 75 },
      history: [
        { icon: 'fa-pen', cls: 'act-meet', text: 'Ольга Зайцева обновила спецификацию', time: '03.08 15:00' },
        { icon: 'fa-plus', cls: 'act-call', text: 'Добавлен контакт «Максим Орехов»', time: '01.08 12:00' },
        { icon: 'fa-robot', cls: 'act-mail', text: 'Автоматическое обновление статуса проекта', time: '28.07 18:00' },
      ],
      nextSteps: [
        { icon: 'fa-phone', text: 'Позвонить Андрею — подтвердить спецификацию' },
        { icon: 'fa-paper-plane', text: 'Отправить финальное КП по проекту «НПЗ»' },
        { icon: 'fa-calendar', text: 'Назначить встречу с Натальей на среду' },
      ],
      tasks: [
        { text: 'Подготовить финальное КП по НПЗ', due: 'До 10 августа', overdue: false },
        { text: 'Согласовать спецификацию с техотделом', due: 'До 12 августа', overdue: false },
        { text: 'Отправить договор на подпись', due: 'До 15 августа', overdue: false },
      ],
      activities: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Андрею Козлову', time: '03.08 16:00' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'Спецификация оборудования', time: '01.08 11:20' },
        { icon: 'fa-video', cls: 'act-meet', text: 'Техническая встреча — НПЗ', time: '28.07 14:00' },
      ],
    },
    { n: 'НЕФТЬ-ГАЗ, ООО', inn: '6450605920', c: 'linear-gradient(135deg,#ec4899,#f59e0b)', deal: '30.07.2026 16:00', date: '01.12.2025', resp: 'Анна Ковалёва', path: '',
      industry: 'Нефтегаз', city: 'Самара', employees: 500, rating: 4.3, clientSince: 2018, revenue: '≈ 1,2 млрд ₽',
      phone: '+7 846 456-78-90', email: 'info@neftgaz-samara.ru', comments: [],
      contacts: [
        { name: 'Роман Сидоров', role: 'Ген. директор', tag: 'ЛПР', av: 'РС' },
        { name: 'Татьяна Кузнецова', role: 'Начальник закупок', tag: 'контракт', av: 'ТК' },
        { name: 'Игорь Васильев', role: 'Тех. директор', tag: 'ТЗ', av: 'ИВ' },
        { name: 'Анна Михайлова', role: 'Бухгалтерия', tag: 'оплата', av: 'АМ' },
      ],
      related: [{ name: 'НефтеПром, АО', type: 'Материнская компания', icon: 'fa-building' }, { name: 'ГазСнаб, ООО', type: 'Дочерняя компания', icon: 'fa-building' }],
      source: 'Реферал', tags: ['Нефтегаз', 'Крупный', 'Стратегический'],
      totalRevenue: '22,0 млн ₽', totalDeals: 10, avgCheck: '2,2 млн ₽',
      desc: 'НЕФТЬ-ГАЗ — крупный нефтегазовый холдинг в Самаре. Один из топ-3 клиентов по объёму закупок. Работаем с 2018 года, стабильный рост.',
      insights: [
        { type: 'red', icon: 'fa-triangle-exclamation', title: 'Риск — просрочка оплаты', desc: 'Оплата по счёту №С-9845 задерживается на 14 дней. Сумма 2,4 млн ₽. Рекомендуем личный звонок.', risk: 70, btn: 'Позвонить в бухгалтерию' },
        { type: 'green', icon: 'fa-arrow-trend-up', title: 'Крупный проект', desc: 'Клиент планирует модернизацию НПЗ. Потенциал сделки 15-20 млн ₽.', btn: 'Подготовить предложение' },
        { type: 'yellow', icon: 'fa-clock-rotate-left', title: 'Контракт истекает через 60 дней', desc: 'Договор №2024-001 требует продления. Начать переговоры сейчас.' },
        { type: 'blue', icon: 'fa-lightbulb', title: 'Рекомендация', desc: 'Роман Сидоров упомянул интерес к новой линейке «Энерго-Плюс». Отправить информацию.' },
      ],
      dealsList: [
        { name: 'Модернизация НПЗ — этап 1', sub: 'Открыта 30.07 · Анна Ковалёва', stage: 'Переговоры', stageClass: 'b-blue', sum: '8 500 000 ₽' },
        { name: 'Годовой контракт 2026', sub: 'Открыта 25.07 · Анна Ковалёва', stage: 'Договор', stageClass: 'b-yellow', sum: '12 000 000 ₽' },
        { name: 'Поставка запчастей Q3', sub: 'Открыта 20.07 · Анна Ковалёва', stage: 'Квалификация', stageClass: 'b-blue', sum: '3 200 000 ₽' },
      ],
      dealsClosed: [
        { name: 'Годовой контракт 2025', sub: 'Закрыта 15.01', stage: 'Выиграна', stageClass: 'b-green', sum: '18 500 000 ₽' },
        { name: 'Поставка насосного оборудования', sub: 'Закрыта 10.06', stage: 'Выиграна', stageClass: 'b-green', sum: '4 700 000 ₽' },
      ],
      commsHistory: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Роману Сидорову — обсуждение модернизации', time: '30.07 16:00 · 25 мин' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'Письмо: КП по модернизации НПЗ', time: '28.07 10:30' },
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Татьяне Кузнецовой — уточнение сроков', time: '25.07 14:00 · 12 мин' },
        { icon: 'fa-video', cls: 'act-meet', text: 'Совещание по контракту 2026', time: '20.07 11:00 · 1 час' },
      ],
      contacts: [
        { name: 'Роман Сидоров', role: 'Ген. директор · +7 846 456-78-90', av: 'РС' },
        { name: 'Татьяна Кузнецова', role: 'Начальник закупок · +7 846 456-78-91', av: 'ТК' },
        { name: 'Игорь Васильев', role: 'Тех. директор · +7 846 456-78-92', av: 'ИВ' },
        { name: 'Анна Михайлова', role: 'Бухгалтерия · +7 846 456-78-93', av: 'АМ' },
      ],
      docs: [
        { name: 'Договор №2024-001', icon: 'fa-file-contract', meta: 'PDF · 680 КБ · 01.12.2024' },
        { name: 'КП «Модернизация НПЗ»', icon: 'fa-file-invoice-dollar', meta: 'PDF · 2.1 МБ · 28.07.2026' },
        { name: 'Счёт №С-9845', icon: 'fa-receipt', meta: 'PDF · 110 КБ · 15.07.2026' },
        { name: 'Техническое задание', icon: 'fa-file-lines', meta: 'PDF · 3.5 МБ · 20.07.2026' },
        { name: 'Акт сверки взаиморасчётов', icon: 'fa-file-invoice', meta: 'PDF · 65 КБ · 01.07.2026' },
      ],
      analytics: { q1: 60, q2: 70, q3: 65, q4: 80 },
      history: [
        { icon: 'fa-pen', cls: 'act-meet', text: 'Анна Ковалёва обновила сумму сделки', time: '30.07 15:00' },
        { icon: 'fa-plus', cls: 'act-call', text: 'Добавлен контакт «Анна Михайлова»', time: '25.07 12:00' },
        { icon: 'fa-robot', cls: 'act-mail', text: 'Автоматическое напоминание о просрочке', time: '15.07 10:00' },
        { icon: 'fa-pen', cls: 'act-meet', text: 'Обновлена спецификация по НПЗ', time: '10.07 14:00' },
      ],
      nextSteps: [
        { icon: 'fa-phone', text: 'Позвонить Роману — обсудить просрочку' },
        { icon: 'fa-paper-plane', text: 'Отправить напоминание об оплате' },
        { icon: 'fa-calendar', text: 'Назначить встречу по контракту 2026' },
        { icon: 'fa-file', text: 'Подготовить допсоглашение' },
      ],
      tasks: [
        { text: 'Решить вопрос с просрочкой оплаты', due: 'Просрочено · 16 июля', overdue: true },
        { text: 'Подготовить контракт 2026', due: 'До 15 августа', overdue: false },
        { text: 'Согласовать спецификацию по НПЗ', due: 'До 10 августа', overdue: false },
        { text: 'Отправить информацию по «Энерго-Плюс»', due: 'До 5 августа', overdue: false },
      ],
      activities: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Роману Сидорову', time: '30.07 16:00' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'КП по модернизации НПЗ', time: '28.07 10:30' },
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Татьяне Кузнецовой', time: '25.07 14:00' },
        { icon: 'fa-video', cls: 'act-meet', text: 'Совещание по контракту 2026', time: '20.07 11:00' },
      ],
    },
    { n: 'ТГС, ООО', inn: '7825665993', c: 'linear-gradient(135deg,#0ea5e9,#3b82f6)', deal: '29.07.2026 16:00', date: '01.12.2025', resp: 'Пётр Васильев', path: '',
      industry: 'Технологии', city: 'Москва', employees: 60, rating: 4.7, clientSince: 2023, revenue: '≈ 95 млн ₽',
      phone: '+7 495 567-89-01', email: 'hello@tgs.tech', comments: [],
      contacts: [
        { name: 'Мария Лебедева', role: 'CEO', tag: 'ЛПР', av: 'МЛ' },
        { name: 'Дмитрий Серов', role: 'CTO', tag: 'техспец', av: 'ДС' },
      ],
      related: [], source: 'Сайт', tags: ['Технологии', 'Стартап', 'SaaS'],
      totalRevenue: '3,1 млн ₽', totalDeals: 4, avgCheck: '0,8 млн ₽',
      desc: 'ТГС — технологическая компания, разработчик SaaS-платформы для автоматизации бизнес-процессов. Молодой быстрорастущий клиент.',
      insights: [
        { type: 'green', icon: 'fa-arrow-trend-up', title: 'Быстрый рост', desc: 'Клиент увеличил число пользователей на 50% за квартал. Готов к расширению.', btn: 'Предложить тариф Pro' },
        { type: 'blue', icon: 'fa-lightbulb', title: 'Реферальная программа', desc: 'Мария Лебедева активно рекомендует нас. Запустить программу лояльности.' },
      ],
      dealsList: [
        { name: 'Расширение лицензий', sub: 'Открыта 29.07 · Пётр Васильев', stage: 'Квалификация', stageClass: 'b-blue', sum: '960 000 ₽' },
      ],
      dealsClosed: [
        { name: 'Базовый тариф 2025', sub: 'Закрыта 15.03', stage: 'Выиграна', stageClass: 'b-green', sum: '480 000 ₽' },
      ],
      commsHistory: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Марии Лебедевой — обсуждение расширения', time: '29.07 16:00 · 10 мин' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'Письмо: тарифы и лицензии', time: '28.07 11:00' },
      ],
      contacts: [
        { name: 'Мария Лебедева', role: 'CEO · +7 495 567-89-01', av: 'МЛ' },
        { name: 'Дмитрий Серов', role: 'CTO · +7 495 567-89-02', av: 'ДС' },
      ],
      docs: [
        { name: 'Договор SaaS 2025', icon: 'fa-file-contract', meta: 'PDF · 180 КБ · 15.03.2025' },
        { name: 'КП «Расширение лицензий»', icon: 'fa-file-invoice-dollar', meta: 'PDF · 90 КБ · 29.07.2026' },
      ],
      analytics: { q1: 25, q2: 40, q3: 50, q4: 65 },
      history: [
        { icon: 'fa-plus', cls: 'act-call', text: 'Новая сделка «Расширение лицензий»', time: '29.07 16:00' },
        { icon: 'fa-robot', cls: 'act-mail', text: 'Автоматическое обновление тарифа', time: '15.03 12:00' },
      ],
      nextSteps: [
        { icon: 'fa-phone', text: 'Позвонить Марии — обсудить тариф Pro' },
        { icon: 'fa-paper-plane', text: 'Отправить сравнение тарифов' },
      ],
      tasks: [
        { text: 'Подготовить сравнение тарифов', due: 'До 5 августа', overdue: false },
        { text: 'Согласовать скидку с руководством', due: 'До 8 августа', overdue: false },
      ],
      activities: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Марии Лебедевой', time: '29.07 16:00' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'Тарифы и лицензии', time: '28.07 11:00' },
      ],
    },
    { n: 'ПМТ 96, ООО', inn: '6658021546', c: 'linear-gradient(135deg,#a855f7,#ec4899)', deal: '25.07.2026 11:00', date: '22.11.2025', resp: 'Дмитрий Орлов', path: 'Реклама › Сайт',
      industry: 'Производство', city: 'Екатеринбург', employees: 120, rating: 4.1, clientSince: 2022, revenue: '≈ 160 млн ₽',
      phone: '+7 343 678-90-12', email: 'info@pmt96.ru', comments: [],
      contacts: [
        { name: 'Олег Новиков', role: 'Директор', tag: 'ЛПР', av: 'ОН' },
        { name: 'Светлана Попова', role: 'Начальник производства', tag: 'ТЗ', av: 'СП' },
        { name: 'Алексей Романов', role: 'Снабжение', tag: 'закупки', av: 'АР' },
      ],
      related: [{ name: 'ПМТ-Сервис, ООО', type: 'Дочерняя компания', icon: 'fa-building' }],
      source: 'Реклама на сайте', tags: ['Производство', 'Урал', 'Средний бизнес'],
      totalRevenue: '5,7 млн ₽', totalDeals: 4, avgCheck: '1,4 млн ₽',
      desc: 'ПМТ 96 — производственная компания в Екатеринбурге. Специализируется на металлоконструкциях и промышленном оборудовании. Стабильный клиент с хорошей историей оплат.',
      insights: [
        { type: 'blue', icon: 'fa-lightbulb', title: 'Сезонный спрос', desc: 'Осень — пик заказов. Клиент увеличит закупки на 40% в Q4.', btn: 'Подготовить предложение' },
        { type: 'yellow', icon: 'fa-clock-rotate-left', title: 'Контракт истекает через 30 дней', desc: 'Договор №2023-089 требует продления. Начать переговоры сейчас.' },
      ],
      dealsList: [
        { name: 'Поставка металлоконструкций', sub: 'Открыта 25.07 · Дмитрий Орлов', stage: 'Переговоры', stageClass: 'b-blue', sum: '2 400 000 ₽' },
        { name: 'Обслуживание оборудования', sub: 'Открыта 20.07 · Дмитрий Орлов', stage: 'Согласование КП', stageClass: 'b-yellow', sum: '800 000 ₽' },
      ],
      dealsClosed: [
        { name: 'Годовой контракт 2025', sub: 'Закрыта 10.01', stage: 'Выиграна', stageClass: 'b-green', sum: '4 200 000 ₽' },
      ],
      commsHistory: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Олегу Новикову — обсуждение Q4', time: '25.07 11:00 · 15 мин' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'Письмо: КП по металлоконструкциям', time: '22.07 10:00' },
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Алексею Романову — уточнение ТЗ', time: '18.07 14:30 · 8 мин' },
      ],
      contacts: [
        { name: 'Олег Новиков', role: 'Директор · +7 343 678-90-12', av: 'ОН' },
        { name: 'Светлана Попова', role: 'Начальник производства · +7 343 678-90-13', av: 'СП' },
        { name: 'Алексей Романов', role: 'Снабжение · +7 343 678-90-14', av: 'АР' },
      ],
      docs: [
        { name: 'Договор №2023-089', icon: 'fa-file-contract', meta: 'PDF · 340 КБ · 22.11.2023' },
        { name: 'КП «Металлоконструкции»', icon: 'fa-file-invoice-dollar', meta: 'PDF · 170 КБ · 22.07.2026' },
        { name: 'Счёт №С-5567', icon: 'fa-receipt', meta: 'PDF · 80 КБ · 20.07.2026' },
      ],
      analytics: { q1: 35, q2: 45, q3: 40, q4: 55 },
      history: [
        { icon: 'fa-pen', cls: 'act-meet', text: 'Дмитрий Орлов обновил сумму сделки', time: '25.07 10:00' },
        { icon: 'fa-robot', cls: 'act-mail', text: 'Напоминание о продлении контракта', time: '22.07 09:00' },
      ],
      nextSteps: [
        { icon: 'fa-phone', text: 'Позвонить Олегу — обсудить продление' },
        { icon: 'fa-paper-plane', text: 'Отправить КП по обслуживанию' },
      ],
      tasks: [
        { text: 'Подготовить КП по обслуживанию', due: 'До 1 августа', overdue: false },
        { text: 'Согласовать продление контракта', due: 'До 10 августа', overdue: false },
        { text: 'Запросить ТЗ у Светланы', due: 'До 3 августа', overdue: false },
      ],
      activities: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Олегу Новикову', time: '25.07 11:00' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'КП по металлоконструкциям', time: '22.07 10:00' },
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Алексею Романову', time: '18.07 14:30' },
      ],
    },
    { n: 'ООО "ТРИА СТРОЙ"', inn: '7710901234', c: 'linear-gradient(135deg,#6366f1,#3b82f6)', deal: '20.07.2026 10:00', date: '10.11.2025', resp: 'Общие компании', path: '',
      industry: 'Строительство', city: 'Москва', employees: 300, rating: 4.4, clientSince: 2021, revenue: '≈ 450 млн ₽',
      phone: '+7 495 789-01-23', email: 'office@triastroi.ru', comments: [],
      contacts: [
        { name: 'Виктор Семёнов', role: 'Ген. директор', tag: 'ЛПР', av: 'ВС' },
        { name: 'Елена Крылова', role: 'Коммерческий директор', tag: 'контракт', av: 'ЕК' },
        { name: 'Андрей Зайцев', role: 'Главный инженер', tag: 'ТЗ', av: 'АЗ' },
        { name: 'Ольга Морозова', role: 'Снабжение', tag: 'закупки', av: 'ОМ' },
      ],
      related: [{ name: 'Триа-Инвест, АО', type: 'Материнская компания', icon: 'fa-building' }, { name: 'СтройАльянс, ООО', type: 'Партнёр', icon: 'fa-handshake' }],
      source: 'Общие компании', tags: ['Строительство', 'Москва', 'Крупный'],
      totalRevenue: '7,3 млн ₽', totalDeals: 5, avgCheck: '1,5 млн ₽',
      desc: 'ООО "ТРИА СТРОЙ" — крупная строительная компания в Москве. Специализируется на жилом и коммерческом строительстве. Один из крупнейших клиентов по объёму.',
      insights: [
        { type: 'green', icon: 'fa-arrow-trend-up', title: 'Стабильный рост', desc: 'Объём закупок вырос на 20% за год. Рекомендуем предложить VIP-условия.', btn: 'Предложить VIP' },
        { type: 'blue', icon: 'fa-lightbulb', title: 'Новый проект', desc: 'Клиент начинает строительство ЖК «Премиум». Потенциал сделки 25+ млн ₽.', btn: 'Назначить встречу' },
        { type: 'yellow', icon: 'fa-clock-rotate-left', title: 'Дедлайн поставки — 10 дней', desc: 'Поставка оборудования для ЖК «Премиум» до 30 июля. Убедиться в готовности.' },
        { type: 'red', icon: 'fa-triangle-exclamation', title: 'Задержка оплаты', desc: 'Счёт №С-8834 оплачен на 70%. Остаток 1,2 млн ₽. Напомнить.', risk: 35 },
      ],
      dealsList: [
        { name: 'Поставка для ЖК «Премиум»', sub: 'Открыта 20.07 · Елена Крылова', stage: 'Договор', stageClass: 'b-yellow', sum: '5 800 000 ₽' },
        { name: 'Комплексная поставка Q3', sub: 'Открыта 15.07 · Елена Крылова', stage: 'Переговоры', stageClass: 'b-blue', sum: '3 200 000 ₽' },
        { name: 'Обслуживание инженерных систем', sub: 'Открыта 10.07 · Елена Крылова', stage: 'Квалификация', stageClass: 'b-blue', sum: '1 500 000 ₽' },
      ],
      dealsClosed: [
        { name: 'Годовой контракт 2025', sub: 'Закрыта 15.01', stage: 'Выиграна', stageClass: 'b-green', sum: '12 400 000 ₽' },
        { name: 'Поставка для ЖК «Комфорт»', sub: 'Закрыта 10.04', stage: 'Выиграна', stageClass: 'b-green', sum: '4 600 000 ₽' },
      ],
      commsHistory: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Виктору Семёнову — обсуждение ЖК «Премиум»', time: '20.07 10:00 · 20 мин' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'Письмо: КП по ЖК «Премиум»', time: '18.07 11:30' },
        { icon: 'fa-video', cls: 'act-meet', text: 'Совещание по поставкам Q3', time: '15.07 14:00 · 1 час' },
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Ольге Морозовой — уточнение спецификации', time: '12.07 10:00 · 12 мин' },
      ],
      contacts: [
        { name: 'Виктор Семёнов', role: 'Ген. директор · +7 495 789-01-23', av: 'ВС' },
        { name: 'Елена Крылова', role: 'Коммерческий директор · +7 495 789-01-24', av: 'ЕК' },
        { name: 'Андрей Зайцев', role: 'Главный инженер · +7 495 789-01-25', av: 'АЗ' },
        { name: 'Ольга Морозова', role: 'Снабжение · +7 495 789-01-26', av: 'ОМ' },
      ],
      docs: [
        { name: 'Договор №2021-045', icon: 'fa-file-contract', meta: 'PDF · 520 КБ · 10.11.2021' },
        { name: 'КП «ЖК Премиум»', icon: 'fa-file-invoice-dollar', meta: 'PDF · 1.8 МБ · 18.07.2026' },
        { name: 'Счёт №С-8834', icon: 'fa-receipt', meta: 'PDF · 95 КБ · 15.07.2026' },
        { name: 'Спецификация Q3', icon: 'fa-file-lines', meta: 'PDF · 2.3 МБ · 10.07.2026' },
        { name: 'Акт приёмки №078', icon: 'fa-receipt', meta: 'PDF · 70 КБ · 10.04.2026' },
      ],
      analytics: { q1: 40, q2: 50, q3: 55, q4: 70 },
      history: [
        { icon: 'fa-pen', cls: 'act-meet', text: 'Елена Крылова обновила спецификацию', time: '20.07 09:00' },
        { icon: 'fa-plus', cls: 'act-call', text: 'Добавлен контакт «Ольга Морозова»', time: '15.07 12:00' },
        { icon: 'fa-robot', cls: 'act-mail', text: 'Автоматическое напоминание о дедлайне', time: '10.07 10:00' },
        { icon: 'fa-pen', cls: 'act-meet', text: 'Обновлена сумма сделки', time: '05.07 14:00' },
      ],
      nextSteps: [
        { icon: 'fa-phone', text: 'Позвонить Виктору — подтвердить поставку' },
        { icon: 'fa-paper-plane', text: 'Отправить напоминание об оплате (30%)' },
        { icon: 'fa-calendar', text: 'Назначить встречу по ЖК «Премиум»' },
        { icon: 'fa-file', text: 'Подготовить допсоглашение на Q3' },
      ],
      tasks: [
        { text: 'Подтвердить поставку для ЖК «Премиум»', due: 'До 25 июля', overdue: true },
        { text: 'Напомнить об оплате (30% — 1,2 млн ₽)', due: 'До 28 июля', overdue: false },
        { text: 'Подготовить допсоглашение Q3', due: 'До 30 июля', overdue: false },
        { text: 'Согласовать спецификацию с Ольгой', due: 'До 1 августа', overdue: false },
      ],
      activities: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Виктору Семёнову', time: '20.07 10:00' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'КП по ЖК «Премиум»', time: '18.07 11:30' },
        { icon: 'fa-video', cls: 'act-meet', text: 'Совещание по поставкам Q3', time: '15.07 14:00' },
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок Ольге Морозовой', time: '12.07 10:00' },
      ],
    },
    { n: 'Ромашка ООО', inn: '7736050003', c: 'linear-gradient(135deg,#34d399,#10b981)', deal: '14.09.2026 14:00', date: '01.03.2024', resp: 'Анна Ковалёва', path: '',
      industry: 'Ритейл', city: 'Москва', employees: 85, rating: 4.6, clientSince: 2022, revenue: '≈ 210 млн ₽',
      phone: '+7 916 234-11-22', email: 'info@romashka.ru', comments: [],
      contacts: [{ name: 'Игорь Смирнов', role: 'Ген. директор', tag: 'ЛПР', av: 'ИС' }, { name: 'Ольга Крылова', role: 'Закупки', tag: 'контракт', av: 'ОК' }],
      related: [], source: 'Рекомендация', tags: ['Ритейл', 'Москва', 'VIP'],
      totalRevenue: '₽ 5,4М', totalDeals: 3, avgCheck: '₽ 1,8М',
      desc: 'Ромашка ООО — сеть розничных магазинов электроники. Клиент с 2022 года, стабильные закупки.',
      insights: [{ type: 'green', icon: 'fa-arrow-trend-up', title: 'Растущий клиент', desc: 'Объём закупок вырос на 25% за квартал.' }],
      dealsList: [{ name: 'Поставка оборудования Q4', sub: 'Открыта 14.09 · Анна Ковалёва', stage: 'Переговоры', stageClass: 'b-blue', sum: '₽ 5 400 000' }],
      dealsClosed: [], commsHistory: [{ icon: 'fa-phone', cls: 'act-call', text: 'Звонок Игорю Смирнову', time: 'Сегодня 10:00 · 12 мин' }],
      docs: [{ name: 'КП «Ромашка» v3.pdf', icon: 'fa-file-pdf', meta: 'PDF · 320 КБ' }],
      analytics: { q1: 30, q2: 45, q3: 50, q4: 60 },
      history: [], nextSteps: [{ icon: 'fa-phone', text: 'Позвонить Игорю — обсудить условия' }],
      tasks: [{ text: 'Отправить финальное КП', due: 'До 16:00', overdue: false }],
      activities: [{ icon: 'fa-phone', cls: 'act-call', text: 'Звонок Игорю', time: 'Сегодня 10:00' }],
    },
    { n: 'ТехноСфера', inn: '7814001234', c: 'linear-gradient(135deg,#3b82f6,#6366f1)', deal: '27.08.2026 16:00', date: '15.06.2025', resp: 'Дмитрий Орлов', path: '',
      industry: 'IT', city: 'Санкт-Петербург', employees: 45, rating: 4.4, clientSince: 2025, revenue: '≈ 80 млн ₽',
      phone: '+7 903 555-01-09', email: 'info@technosphere.ru', comments: [],
      contacts: [{ name: 'Мария Петрова', role: 'Финансовый директор', tag: 'ЛПР', av: 'МП' }],
      related: [], source: 'Сайт', tags: ['IT', 'СПб'],
      totalRevenue: '₽ 2,1М', totalDeals: 1, avgCheck: '₽ 2,1М',
      desc: 'ТехноСфера — IT-компания, разработчик корпоративных решений.',
      insights: [{ type: 'yellow', icon: 'fa-clock-rotate-left', title: 'Ожидает ответа', desc: 'КП отправлено, ответа нет 3 дня.' }],
      dealsList: [{ name: 'Внедрение CRM', sub: 'Открыта 27.08 · Дмитрий Орлов', stage: 'Квалификация', stageClass: 'b-blue', sum: '₽ 2 100 000' }],
      dealsClosed: [], commsHistory: [], docs: [],
      analytics: { q1: 20, q2: 30, q3: 35, q4: 45 },
      history: [], nextSteps: [{ icon: 'fa-phone', text: 'Позвонить Марии — уточнить бюджет' }],
      tasks: [], activities: [],
    },
    { n: 'ГринЛайт', inn: '7705006789', c: 'linear-gradient(135deg,#10b981,#059669)', deal: '03.08.2026 16:00', date: '10.01.2026', resp: 'Анна Ковалёва', path: '',
      industry: 'Энергетика', city: 'Москва', employees: 120, rating: 4.7, clientSince: 2024, revenue: '≈ 350 млн ₽',
      phone: '+7 921 777-33-44', email: 'info@greenlight.ru', comments: [],
      contacts: [{ name: 'Олег Кузнецов', role: 'Ген. директор', tag: 'ЛПР', av: 'ОК' }],
      related: [], source: 'Реферал', tags: ['Энергетика', 'Крупный'],
      totalRevenue: '₽ 8,9М', totalDeals: 2, avgCheck: '₽ 4,5М',
      desc: 'ГринЛайт — энергетическая компания. Ключевой клиент.',
      insights: [{ type: 'blue', icon: 'fa-lightbulb', title: 'Договор на подписании', desc: 'Отправлен на подпись КЭП.' }],
      dealsList: [{ name: 'Годовой контракт', sub: 'Открыта 03.08 · Анна Ковалёва', stage: 'Договор', stageClass: 'b-yellow', sum: '₽ 8 900 000' }],
      dealsClosed: [], commsHistory: [{ icon: 'fa-envelope', cls: 'act-mail', text: 'Договор отправлен на подпись', time: '03.08 11:00' }],
      docs: [{ name: 'Договор №2024-089.pdf', icon: 'fa-file-contract', meta: 'PDF · 520 КБ' }],
      analytics: { q1: 60, q2: 70, q3: 65, q4: 80 },
      history: [], nextSteps: [{ icon: 'fa-phone', text: 'Контролировать подпись' }],
      tasks: [], activities: [],
    },
    { n: 'АкваСтрой', inn: '7708003456', c: 'linear-gradient(135deg,#f59e0b,#ef4444)', deal: '04.08.2026 14:00', date: '01.12.2025', resp: 'Дмитрий Орлов', path: '',
      industry: 'Строительство', city: 'Москва', employees: 200, rating: 4.3, clientSince: 2023, revenue: '≈ 480 млн ₽',
      phone: '+7 926 848-77-11', email: 'info@aquastroy.ru', comments: [],
      contacts: [{ name: 'Наталья Волкова', role: 'Главный инженер', tag: 'ТЗ', av: 'НВ' }, { name: 'Сергей Козлов', role: 'Снабжение', tag: 'закупки', av: 'СК' }],
      related: [], source: 'Холодные звонки', tags: ['Строительство', 'Москва'],
      totalRevenue: '₽ 6,7М', totalDeals: 2, avgCheck: '₽ 3,4М',
      desc: 'АкваСтрой — строительная компания, промышленные объекты.',
      insights: [{ type: 'yellow', icon: 'fa-clock-rotate-left', title: 'Ожидает демо', desc: 'Демонстрация назначена на четверг.' }],
      dealsList: [{ name: 'Автоматизация склада', sub: 'Открыта 04.08 · Дмитрий Орлов', stage: 'Переговоры', stageClass: 'b-blue', sum: '₽ 6 700 000' }],
      dealsClosed: [], commsHistory: [], docs: [],
      analytics: { q1: 40, q2: 55, q3: 50, q4: 65 },
      history: [], nextSteps: [{ icon: 'fa-video', text: 'Провести демо в четверг' }],
      tasks: [{ text: 'Подготовить демо-окружение', due: 'До среды', overdue: false }],
      activities: [],
    },
    { n: 'МедиаПлюс', inn: '6602007890', c: 'linear-gradient(135deg,#ec4899,#f59e0b)', deal: '03.08.2026 16:00', date: '15.01.2026', resp: 'Елена Соколова', path: '',
      industry: 'Медиа', city: 'Екатеринбург', employees: 60, rating: 4.5, clientSince: 2026, revenue: '≈ 95 млн ₽',
      phone: '+7 917 222-88-99', email: 'info@mediaplus.ru', comments: [],
      contacts: [{ name: 'Сергей Лебедев', role: 'Ген. директор', tag: 'ЛПР', av: 'СЛ' }],
      related: [], source: 'LinkedIn', tags: ['Медиа', 'Екатеринбург'],
      totalRevenue: '₽ 3,3М', totalDeals: 1, avgCheck: '₽ 3,3М',
      desc: 'МедиаПлюс — медиахолдинг. Сделка закрыта.',
      insights: [{ type: 'green', icon: 'fa-check', title: 'Сделка выиграна', desc: 'Клиент доволен, готов к повторным закупкам.' }],
      dealsList: [], dealsClosed: [{ name: 'Маркетинговая кампания', sub: 'Закрыта 03.08', stage: 'Выиграна', stageClass: 'b-green', sum: '₽ 3 300 000' }],
      commsHistory: [{ icon: 'fa-envelope', cls: 'act-mail', text: 'Благодарственное письмо', time: '03.08 17:00' }],
      docs: [{ name: 'Договор (подписан).pdf', icon: 'fa-file-contract', meta: 'PDF · 280 КБ' }],
      analytics: { q1: 30, q2: 40, q3: 50, q4: 60 },
      history: [], nextSteps: [{ icon: 'fa-heart', text: 'Попросить отзыв' }],
      tasks: [], activities: [],
    },
    { n: 'Финмакс', inn: '7709001111', c: 'linear-gradient(135deg,#f59e0b,#ef4444)', deal: '30.07.2026 16:00', date: '01.12.2025', resp: 'Анна Ковалёва', path: '',
      industry: 'Финансы', city: 'Москва', employees: 300, rating: 4.2, clientSince: 2021, revenue: '≈ 1,5 млрд ₽',
      phone: '+7 999 004-55-66', email: 'info@finmax.ru', comments: [],
      contacts: [{ name: 'Виктор Соловьёв', role: 'Ген. директор', tag: 'ЛПР', av: 'ВС' }],
      related: [], source: 'Выставки', tags: ['Финансы', 'Крупный'],
      totalRevenue: '₽ 14,5М', totalDeals: 3, avgCheck: '₽ 4,8М',
      desc: 'Финмакс — финансовая группа. Крупнейший клиент по сумме.',
      insights: [{ type: 'red', icon: 'fa-triangle-exclamation', title: 'Риск оттока', desc: 'Активность снизилась. Рекомендуем персональное касание.' }],
      dealsList: [{ name: 'Корпоративное обучение', sub: 'Открыта 30.07 · Анна Ковалёва', stage: 'Новые', stageClass: 'b-blue', sum: '₽ 14 500 000' }],
      dealsClosed: [], commsHistory: [], docs: [],
      analytics: { q1: 50, q2: 60, q3: 55, q4: 70 },
      history: [], nextSteps: [{ icon: 'fa-phone', text: 'Первичный звонок Виктору' }],
      tasks: [{ text: 'Подготовить презентацию', due: 'До понедельника', overdue: false }],
      activities: [],
    },
    { n: 'БиоФарм', inn: '5406002222', c: 'linear-gradient(135deg,#10b981,#059669)', deal: '04.08.2026 16:00', date: '01.12.2025', resp: 'Елена Соколова', path: '',
      industry: 'Фарма', city: 'Новосибирск', employees: 150, rating: 4.4, clientSince: 2024, revenue: '≈ 280 млн ₽',
      phone: '+7 963 321-45-67', email: 'info@biopharm.ru', comments: [],
      contacts: [{ name: 'Ирина Морозова', role: 'Руководитель закупок', tag: 'ЛПР', av: 'ИМ' }],
      related: [], source: 'Рекомендация клиента', tags: ['Фарма', 'Новосибирск'],
      totalRevenue: '₽ 4,2М', totalDeals: 1, avgCheck: '₽ 4,2М',
      desc: 'БиоФарм — фармацевтическая компания.',
      insights: [{ type: 'blue', icon: 'fa-lightbulb', title: 'Новый клиент', desc: 'Первая сделка, нужна качественная подготовка.' }],
      dealsList: [{ name: 'Поставка лабораторного оборудования', sub: 'Открыта 04.08 · Елена Соколова', stage: 'Квалификация', stageClass: 'b-blue', sum: '₽ 4 200 000' }],
      dealsClosed: [], commsHistory: [], docs: [],
      analytics: { q1: 20, q2: 30, q3: 35, q4: 50 },
      history: [], nextSteps: [{ icon: 'fa-phone', text: 'Перезвонить Ирине' }],
      tasks: [], activities: [],
    },
  ],

  contacts: [
    { n: 'Алексей Кузнецов', phone: '+7 916 234-56-78', c: 'linear-gradient(135deg,#6366f1,#a855f7)', deal: '14.09.2026 14:00', date: '23.06.2026', resp: 'Анна Ковалёва', path: '',
      company: 'Ромашка ООО', role: 'Ген. директор', email: 'kuznetsov@romashka.ru', city: 'Москва', bday: '15.03.1985',
      industry: 'Ритейл', stage: 'Переговоры', amount: '₽ 5 400 000', prob: 72, comments: [],
      nextSteps: [
        { icon: 'fa-phone', text: 'Позвонить — обсудить условия оплаты', when: 'Сегодня 10:00' },
        { icon: 'fa-file-lines', text: 'Отправить обновлённое КП', when: 'До 16:00' },
      ],
      deals: [{ name: 'Поставка оборудования Q4', amount: '₽ 5 400 000', stage: 'Переговоры', date: '14.09.2026' }],
      comms: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Входящий звонок от Алексея', time: 'Сегодня 09:30 · 8 мин' },
        { icon: 'fa-envelope', cls: 'act-mail', text: 'КП отправлено на почту', time: 'Вчера 16:00' },
      ],
      tasks: [
        { text: 'Подготовить финальное КП', due: 'До 14:00', overdue: false },
        { text: 'Согласовать условия с юристом', due: 'До завтра', overdue: false },
      ],
      docs: [{ name: 'КП «Ромашка» v3.pdf', icon: 'fa-file-pdf', meta: 'PDF · 320 КБ' }],
      history: [
        { icon: 'fa-phone', cls: 'act-call', text: 'Звонок от Алексея', time: 'Сегодня 09:30' },
        { icon: 'fa-plus', cls: 'act-call', text: 'Контакт создан', time: '23.06.2026' },
      ],
    },
    { n: 'Марина Волкова', phone: '+7 903 118-24-90', c: 'linear-gradient(135deg,#ec4899,#a855f7)', deal: '27.08.2026 16:00', date: '23.06.2026', resp: 'Пётр Васильев', path: '',
      company: 'ТехноСфера', role: 'Финансовый директор', email: 'volkova@technosphere.ru', city: 'Санкт-Петербург', bday: '22.07.1990',
      industry: 'IT', stage: 'Квалификация', amount: '₽ 2 100 000', prob: 45, comments: [],
      nextSteps: [
        { icon: 'fa-phone', text: 'Позвонить — уточнить бюджет', when: 'Завтра 11:00' },
      ],
      deals: [{ name: 'Внедрение CRM', amount: '₽ 2 100 000', stage: 'Квалификация', date: '27.08.2026' }],
      comms: [{ icon: 'fa-envelope', cls: 'act-mail', text: 'Письмо с презентацией', time: '25.08 14:00' }],
      tasks: [{ text: 'Запросить ТЗ у Марины', due: 'До 30 августа', overdue: false }],
      docs: [],
      history: [{ icon: 'fa-plus', cls: 'act-call', text: 'Контакт создан', time: '23.06.2026' }],
    },
    { n: 'Дмитрий Соколов', phone: '+7 925 447-19-03', c: 'linear-gradient(135deg,#3b82f6,#6366f1)', deal: '04.08.2026 16:00', date: '17.06.2026', resp: 'Дмитрий Орлов', path: '',
      company: 'АкваСтрой', role: 'Технический директор', email: 'sokolov@aquastroy.ru', city: 'Москва', bday: '10.11.1982',
      industry: 'Строительство', stage: 'Переговоры', amount: '₽ 6 700 000', prob: 58, comments: [],
      nextSteps: [
        { icon: 'fa-video', text: 'Онлайн-демо продукта', when: 'Четверг 14:00' },
      ],
      deals: [{ name: 'Автоматизация склада', amount: '₽ 6 700 000', stage: 'Переговоры', date: '04.08.2026' }],
      comms: [{ icon: 'fa-video', cls: 'act-meet', text: 'Встреча по проекту', time: '01.08 11:00 · 45 мин' }],
      tasks: [{ text: 'Подготовить демо-окружение', due: 'До среды', overdue: false }],
      docs: [{ name: 'ТЗ «Автоматизация склада».pdf', icon: 'fa-file-lines', meta: 'PDF · 1.2 МБ' }],
      history: [{ icon: 'fa-plus', cls: 'act-call', text: 'Контакт создан', time: '17.06.2026' }],
    },
    { n: 'Екатерина Морозова', phone: '+7 909 673-45-12', c: 'linear-gradient(135deg,#10b981,#059669)', deal: '04.08.2026 14:00', date: '10.06.2026', resp: 'Общие контакты', path: 'Прочий трафик › Звонок',
      company: 'БиоФарм', role: 'Руководитель закупок', email: 'morozova@biopharm.ru', city: 'Новосибирск', bday: '05.04.1988',
      industry: 'Фарма', stage: 'Квалификация', amount: '₽ 4 200 000', prob: 50, comments: [],
      nextSteps: [{ icon: 'fa-phone', text: 'Перезвонить — уточнить потребности', when: 'Пятница 10:00' }],
      deals: [{ name: 'Поставка лабораторного оборудования', amount: '₽ 4 200 000', stage: 'Квалификация', date: '04.08.2026' }],
      comms: [{ icon: 'fa-phone', cls: 'act-call', text: 'Входящий звонок', time: '02.08 15:00 · 12 мин' }],
      tasks: [{ text: 'Отправить каталог продукции', due: 'До завтра', overdue: false }],
      docs: [],
      history: [{ icon: 'fa-plus', cls: 'act-call', text: 'Контакт создан', time: '10.06.2026' }],
    },
    { n: 'Сергей Лебедев', phone: '+7 917 802-56-34', c: 'linear-gradient(135deg,#f59e0b,#ef4444)', deal: '03.08.2026 16:00', date: '09.06.2026', resp: 'Ольга Зайцева', path: '',
      company: 'МедиаПлюс', role: 'Генеральный директор', email: 'lebedev@mediaplus.ru', city: 'Екатеринбург', bday: '18.09.1979',
      industry: 'Медиа', stage: 'Выиграно', amount: '₽ 3 300 000', prob: 100, comments: [],
      nextSteps: [{ icon: 'fa-heart', text: 'Попросить отзыв о сотрудничестве', when: 'На этой неделе' }],
      deals: [{ name: 'Маркетинговая кампания', amount: '₽ 3 300 000', stage: 'Выиграно', date: '03.08.2026' }],
      comms: [{ icon: 'fa-envelope', cls: 'act-mail', text: 'Благодарственное письмо', time: '03.08 17:00' }],
      tasks: [],
      docs: [{ name: 'Договор (подписан).pdf', icon: 'fa-file-contract', meta: 'PDF · 280 КБ' }],
      history: [{ icon: 'fa-check', cls: 'act-call', text: 'Сделка закрыта', time: '03.08 16:00' }],
    },
    { n: 'Ольга Новикова', phone: '+7 926 331-90-67', c: 'linear-gradient(135deg,#8b5cf6,#a855f7)', deal: '30.07.2026 16:00', date: '08.06.2026', resp: 'Анна Ковалёва', path: '',
      company: 'Финмакс', role: 'Директор по развитию', email: 'novikova@finmax.ru', city: 'Москва', bday: '30.01.1992',
      industry: 'Финансы', stage: 'Новые', amount: '₽ 14 500 000', prob: 30, comments: [],
      nextSteps: [{ icon: 'fa-phone', text: 'Первичный звонок — представиться', when: 'Понедельник 10:00' }],
      deals: [{ name: 'Корпоративное обучение', amount: '₽ 14 500 000', stage: 'Новые', date: '30.07.2026' }],
      comms: [],
      tasks: [{ text: 'Подготовить презентацию', due: 'До понедельника', overdue: false }],
      docs: [],
      history: [{ icon: 'fa-plus', cls: 'act-call', text: 'Контакт создан', time: '08.06.2026' }],
    },
    { n: 'Иван Петров', phone: '+7 905 214-77-45', c: 'linear-gradient(135deg,#0ea5e9,#3b82f6)', deal: '29.07.2026 16:00', date: '08.06.2026', resp: 'Пётр Васильев', path: 'Прочий трафик › Звонок',
      company: 'ТГС', role: 'CTO', email: 'petrov@tgs.tech', city: 'Москва', bday: '12.06.1987',
      industry: 'Технологии', stage: 'Квалификация', amount: '₽ 960 000', prob: 40, comments: [],
      nextSteps: [{ icon: 'fa-envelope', text: 'Отправить техническую документацию', when: 'Среда' }],
      deals: [{ name: 'Расширение лицензий', amount: '₽ 960 000', stage: 'Квалификация', date: '29.07.2026' }],
      comms: [{ icon: 'fa-phone', cls: 'act-call', text: 'Звонок Ивану', time: '29.07 16:00 · 10 мин' }],
      tasks: [],
      docs: [],
      history: [{ icon: 'fa-plus', cls: 'act-call', text: 'Контакт создан', time: '08.06.2026' }],
    },
    { n: 'Наталья Зайцева', phone: '+7 916 558-03-21', c: 'linear-gradient(135deg,#a855f7,#ec4899)', deal: '28.05.2026 11:00', date: '28.05.2026', resp: 'Дмитрий Орлов', path: '',
      company: 'ПМТ 96', role: 'Начальник производства', email: 'zaitseva@pmt96.ru', city: 'Екатеринбург', bday: '03.08.1991',
      industry: 'Производство', stage: 'Переговоры', amount: '₽ 2 400 000', prob: 55, comments: [],
      nextSteps: [{ icon: 'fa-phone', text: 'Обсудить спецификацию', when: 'Четверг 15:00' }],
      deals: [{ name: 'Поставка металлоконструкций', amount: '₽ 2 400 000', stage: 'Переговоры', date: '28.05.2026' }],
      comms: [{ icon: 'fa-phone', cls: 'act-call', text: 'Звонок Наталье', time: '28.05 11:00 · 15 мин' }],
      tasks: [{ text: 'Подготовить спецификацию', due: 'До четверга', overdue: false }],
      docs: [],
      history: [{ icon: 'fa-plus', cls: 'act-call', text: 'Контакт создан', time: '28.05.2026' }],
    },
    { n: 'Павел Орлов', phone: '+7 903 640-12-88', c: 'linear-gradient(135deg,#6366f1,#3b82f6)', deal: '14.05.2026 10:00', date: '14.05.2026', resp: 'Общие контакты', path: '',
      company: 'Вектор Групп', role: 'Логист', email: 'orlov@vector.ru', city: 'Казань', bday: '25.12.1993',
      industry: 'Логистика', stage: 'Новые', amount: '₽ 1 200 000', prob: 20, comments: [],
      nextSteps: [{ icon: 'fa-phone', text: 'Первичный контакт', when: 'Понедельник 11:00' }],
      deals: [{ name: 'Оптимизация логистики', amount: '₽ 1 200 000', stage: 'Новые', date: '14.05.2026' }],
      comms: [],
      tasks: [],
      docs: [],
      history: [{ icon: 'fa-plus', cls: 'act-call', text: 'Контакт создан', time: '14.05.2026' }],
    },
  ],

  processes: [
    { id: 0, n: 'Договор поставки с ТехноСфера', ic: 'fa-file-contract', c: 'linear-gradient(135deg,#6366f1,#a855f7)', sum: '₽ 2,1М', step: 'Шаг 2/4 · ваша подпись', from: 'Анна Ковалёва', st: 'На согласовании', stc: 'background:rgba(245,158,11,.35);color:#fbbf24',
      topic: 'Договор поставки с ТехноСфера', date: '23 июля 2026', threshold: 'Согласование договора > 5 млн',
      files: [{ name: 'Договор №445.pdf', icon: 'fa-file-pdf' }],
      route: [
        { step: 'Создание', done: true, who: 'Анна Ковалёва', role: 'Инициатор', ic: 'АК', bg: 'linear-gradient(135deg,#f59e0b,#ef4444)' },
        { step: 'Согласование (юрист)', done: true, who: 'Максим Титов', role: 'Юрист', ic: 'МТ', bg: 'linear-gradient(135deg,#6366f1,#a855f7)' },
        { step: 'Согласование (руководитель)', done: true, who: 'Пётр Васильев', role: 'CEO', ic: 'ПВ', bg: 'linear-gradient(135deg,#8b5cf6,#ec4899)' },
        { step: 'Подпись — сейчас', current: true, who: 'Пётр Васильев', role: 'Ген. директор', ic: 'ПВ', bg: 'linear-gradient(135deg,#ec4899,#f59e0b)' },
      ],
      discussion: [
        { who: 'Анна Ковалёва', av: 'АК', avc: 'linear-gradient(135deg,#f59e0b,#ef4444)', time: '23 июля 09:15', text: 'Запустила процесс согласования договора с ТехноСфера. Прошу всех ознакомиться и утвердить до конца недели.' },
        { who: 'Максим Титов', av: 'МТ', avc: 'linear-gradient(135deg,#6366f1,#a855f7)', time: '23 июля 11:40', text: 'Юридическая проверка пройдена. Замечаний нет. Рекомендую к утверждению.', system: '✅ Юридическое согласование завершено' },
        { who: 'Пётр Васильев', av: 'ПВ', avc: 'linear-gradient(135deg,#8b5cf6,#ec4899)', time: '24 июля 10:00', text: 'Ознакомился с договором. Есть вопрос по п.4.3 — прошу уточнить сроки поставки.' },
        { who: 'Анна Ковалёва', av: 'АК', avc: 'linear-gradient(135deg,#f59e0b,#ef4444)', time: '24 июля 11:20', text: 'Пётр, уточнила у клиента — сроки фиксируем 30 рабочих дней. Обновила договор.', replyTo: 2 },
      ],
    },
    { id: 1, n: 'Договор с ГринЛайт', ic: 'fa-file-contract', c: 'linear-gradient(135deg,#10b981,#059669)', sum: '₽ 8,9М', step: 'Завершён · подписан КЭП', from: 'Анна Ковалёва', st: 'Завершён', stc: 'background:rgba(52,211,153,.35);color:#34d399',
      topic: 'Договор с ГринЛайт', date: '15 января 2026', threshold: '—',
      files: [{ name: 'Договор ГринЛайт.pdf', icon: 'fa-file-pdf' }],
      route: [
        { step: 'Создание', done: true, who: 'Анна Ковалёва', role: 'Инициатор', ic: 'АК', bg: 'linear-gradient(135deg,#f59e0b,#ef4444)' },
        { step: 'Согласование (юрист)', done: true, who: 'Максим Титов', role: 'Юрист', ic: 'МТ', bg: 'linear-gradient(135deg,#6366f1,#a855f7)' },
        { step: 'Подпись КЭП', done: true, who: 'Пётр Васильев', role: 'Ген. директор', ic: 'ПВ', bg: 'linear-gradient(135deg,#8b5cf6,#ec4899)' },
        { step: 'Уведомление', done: true, who: 'Автоматически', role: 'CRM', ic: '1С', bg: 'linear-gradient(135deg,#6b7280,#4b5563)' },
      ],
      discussion: [
        { who: 'Анна Ковалёва', av: 'АК', avc: 'linear-gradient(135deg,#f59e0b,#ef4444)', time: '15 января 09:00', text: 'Договор подписан КЭП. Клиент получил копию. Сделка закрыта.' },
        { who: 'Система', av: '', avc: '', time: '15 января 09:01', text: 'Процесс завершён. Договор подписан электронной подписью.', system: true },
      ],
    },
    { id: 2, n: 'Согласование счёта №1023 (Ромашка)', ic: 'fa-file-invoice', c: 'linear-gradient(135deg,#a855f7,#ec4899)', sum: '₽ 5,4М', step: 'Шаг 2/3 · у юриста', from: 'Вы', st: 'В работе', stc: 'background:rgba(99,102,241,.35);color:#818cf8',
      topic: 'Согласование счёта №1023 (Ромашка)', date: '25 июля 2026', threshold: 'Согласование счёта > 3 млн',
      files: [{ name: 'Счёт №1023.pdf', icon: 'fa-file-invoice' }],
      route: [
        { step: 'Создание', done: true, who: 'Вы', role: 'Инициатор', ic: 'АИ', bg: 'linear-gradient(135deg,#6366f1,#a855f7)' },
        { step: 'Согласование (юрист)', current: true, who: 'Максим Титов', role: 'Юрист', ic: 'МТ', bg: 'linear-gradient(135deg,#6366f1,#a855f7)' },
        { step: 'Утверждение', done: false, who: 'Пётр Васильев', role: 'CEO', ic: 'ПВ', bg: 'linear-gradient(135deg,#8b5cf6,#ec4899)' },
      ],
      discussion: [
        { who: 'Вы', av: 'АИ', avc: 'linear-gradient(135deg,#6366f1,#a855f7)', time: '25 июля 14:00', text: 'Счёт на согласование. Клиент ждёт подтверждения до пятницы.' },
      ],
    },
    { id: 3, n: 'Договор с Финмакс', ic: 'fa-file-signature', c: 'linear-gradient(135deg,#f59e0b,#ef4444)', sum: '₽ 14,5М', step: 'Просрочен 1 дн', from: 'Дмитрий Орлов', st: 'Просрочен', stc: 'background:rgba(239,68,68,.35);color:#f87171',
      topic: 'Договор с Финмакс', date: '18 июля 2026', threshold: 'Договор > 10 млн',
      files: [{ name: 'Договор Финмакс.pdf', icon: 'fa-file-pdf' }],
      route: [
        { step: 'Создание', done: true, who: 'Дмитрий Орлов', role: 'Инициатор', ic: 'ДО', bg: 'linear-gradient(135deg,#6366f1,#a855f7)' },
        { step: 'Согласование (юрист)', done: true, who: 'Максим Титов', role: 'Юрист', ic: 'МТ', bg: 'linear-gradient(135deg,#6366f1,#a855f7)' },
        { step: 'Согласование (руководитель)', current: true, who: 'Пётр Васильев', role: 'CEO', ic: 'ПВ', bg: 'linear-gradient(135deg,#8b5cf6,#ec4899)', overdue: true },
      ],
      discussion: [
        { who: 'Дмитрий Орлов', av: 'ДО', avc: 'linear-gradient(135deg,#6366f1,#a855f7)', time: '18 июля 10:00', text: 'Договор отправлен на согласование. Сумма крупная — прошу ускорить.' },
        { who: 'Максим Титов', av: 'МТ', avc: 'linear-gradient(135deg,#6366f1,#a855f7)', time: '19 июля 15:30', text: 'Юридическая проверка завершена. Замечания есть — см. комментарий к п.7.', system: '✅ Юридическое согласование завершено' },
        { who: 'Дмитрий Орлов', av: 'ДО', avc: 'linear-gradient(135deg,#6366f1,#a855f7)', time: '20 июля 09:00', text: 'Исправил п.7 по замечаниям. Договор повторно отправлен на подпись.' },
        { who: 'Система', av: '', avc: '', time: '22 июля 10:00', text: 'Дедлайн согласования прошёл. Процесс просрочен на 1 день.', system: true },
      ],
    },
  ],

  boards: {
    lanes: [
      {
        name: 'Пилот MVP', cnt: 8, open: true,
        cols: [
          [{ t: 'Полное ТЗ по продукту', bar: '#6366f1', tags: [['Эпик', 'rgba(99,102,241,.35)', '#a5b4fc']], prio: 'Средний' }],
          [{ t: 'Разработка кабинета аналитики', bar: '#f59e0b', av: 'АК', avc: 'linear-gradient(135deg,#f59e0b,#ef4444)', prio: 'Высокий' },
           { t: 'Допилить UI иконок', bar: '#34d399', av: 'АК', avc: 'linear-gradient(135deg,#f59e0b,#ef4444)', prio: 'Низкий' }],
          [{ t: 'Разработка профиля автора', bar: '#f472b6', av: 'АК', avc: 'linear-gradient(135deg,#f59e0b,#ef4444)', due: ['7д', 'rgba(239,68,68,.85)'], prio: 'Высокий' }],
          [{ t: 'Собрать MVP приложение', bar: '#34d399', avs: [['МТ', 'linear-gradient(135deg,#6366f1,#a855f7)'], ['АК', 'linear-gradient(135deg,#f59e0b,#ef4444)']], prio: 'Высокий' }]
        ]
      },
      {
        name: 'Спринт 12 · Backend', cnt: 5, open: false,
        cols: [
          [{ t: 'Настроить очереди SLA для Service Desk', bar: '#818cf8', av: 'ДО', avc: 'linear-gradient(135deg,#6366f1,#a855f7)', prio: 'Средний' }],
          [{ t: 'API интеграции с 1С и Telegram', bar: '#fbbf24', av: 'ДО', avc: 'linear-gradient(135deg,#6366f1,#a855f7)', block: true, tags: [['Заблокировано', 'rgba(239,68,68,.35)', '#f87171']], prio: 'Высокий' },
           { t: 'Автоматизация: триггер «Готово → уведомление»', bar: '#a855f7', av: 'ОЗ', avc: 'linear-gradient(135deg,#8b5cf6,#ec4899)', prio: 'Средний' }],
          [],
          [{ t: 'Настройка ролей RBAC и SSO', bar: '#34d399', av: 'МТ', avc: 'linear-gradient(135deg,#6366f1,#a855f7)', prio: 'Низкий' }]
        ]
      }
    ]
  },

  marketing: {
    campaigns: [
      { n: 'Чёрная пятница 2026', ic: 'fa-tags', c: 'linear-gradient(135deg,#6366f1,#a855f7)', ch: 'Все каналы', budget: '₽ 850К', roi: '412%', leads: '642', conv: '6.1%', st: 'Активна', stc: 'background:rgba(52,211,153,.35);color:#34d399' },
      { n: 'Welcome-цепочка новичков', ic: 'fa-hand-sparkles', c: 'linear-gradient(135deg,#34d399,#10b981)', ch: 'Email · SMS', budget: '₽ 90К', roi: '640%', leads: '318', conv: '8.4%', st: 'Активна', stc: 'background:rgba(52,211,153,.35);color:#34d399' },
      { n: 'Ретаргетинг брошенных корзин', ic: 'fa-cart-arrow-down', c: 'linear-gradient(135deg,#f59e0b,#ef4444)', ch: 'Директ · VK', budget: '₽ 420К', roi: '305%', leads: '489', conv: '5.2%', st: 'Активна', stc: 'background:rgba(52,211,153,.35);color:#34d399' },
      { n: 'Дайджест новинок · Telegram', ic: 'fa-telegram', c: 'linear-gradient(135deg,#2aabee,#1e88e5)', ch: 'Telegram', budget: '₽ 60К', roi: '210%', leads: '221', conv: '3.9%', st: 'Активна', stc: 'background:rgba(52,211,153,.35);color:#34d399' },
      { n: 'Реактивация «Спящие VIP»', ic: 'fa-heart-pulse', c: 'linear-gradient(135deg,#ec4899,#f472b6)', ch: 'WhatsApp + Email', budget: '₽ 180К', roi: '—', leads: '—', conv: '—', st: 'Черновик', stc: 'background:rgba(99,102,241,.35);color:#818cf8' },
      { n: 'День рождения клиента', ic: 'fa-cake-candles', c: 'linear-gradient(135deg,#a855f7,#ec4899)', ch: 'Email · WhatsApp', budget: '₽ 45К', roi: '—', leads: '—', conv: '—', st: 'Черновик', stc: 'background:rgba(99,102,241,.35);color:#818cf8' },
    ],
    segments: [
      { n: 'Спящие VIP', c: 'linear-gradient(135deg,#ec4899,#f472b6)', ic: 'fa-crown', cnt: '312 контактов', tags: [['LTV ₽120К+', 'rgba(236,72,153,.35)', '#f9a8d4'], ['нет покупок 45д', 'rgba(245,158,11,.35)', '#fbbf24']] },
      { n: 'Активные покупатели', c: 'linear-gradient(135deg,#34d399,#10b981)', ic: 'fa-bolt', cnt: '2 480 контактов', tags: [['покупка <30д', 'rgba(52,211,153,.35)', '#34d399'], ['open rate 60%+', 'rgba(99,102,241,.35)', '#a5b4fc']] },
      { n: 'Новые лиды (7 дней)', c: 'linear-gradient(135deg,#6366f1,#a855f7)', ic: 'fa-seedling', cnt: '847 контактов', tags: [['без сделки', 'rgba(99,102,241,.35)', '#a5b4fc'], ['welcome-цепочка', 'rgba(139,92,246,.35)', '#c4b5fd']] },
      { n: 'Lookalike лучших', c: 'linear-gradient(135deg,#a855f7,#c084fc)', ic: 'fa-users-viewfinder', cnt: '1 120 контактов', tags: [['Самостоятельный', 'rgba(99,102,241,.35)', '#a5b4fc'], ['похожесть 92%', 'rgba(52,211,153,.35)', '#34d399']] },
      { n: 'Брошенные корзины', c: 'linear-gradient(135deg,#f59e0b,#ef4444)', ic: 'fa-cart-arrow-down', cnt: '534 контакта', tags: [['корзина <24ч', 'rgba(245,158,11,.35)', '#fbbf24'], ['ретаргетинг', 'rgba(99,102,241,.35)', '#a5b4fc']] },
      { n: 'Отток (риск)', c: 'linear-gradient(135deg,#6b7280,#4b5563)', ic: 'fa-user-slash', cnt: '268 контактов', tags: [['churn 70%+', 'rgba(239,68,68,.35)', '#f87171'], ['удержание', 'rgba(52,211,153,.35)', '#34d399']] },
    ],
    channels: [
      { n: 'Email-рассылки', ic: 'fa-envelope', c: 'linear-gradient(135deg,#ec4899,#f472b6)', roi: '520%', leads: 498, pct: 96 },
      { n: 'Реклама (Директ + VK)', ic: 'fa-rectangle-ad', c: 'linear-gradient(135deg,#6366f1,#a855f7)', roi: '340%', leads: 702, pct: 88 },
      { n: 'WhatsApp', ic: 'fa-brands fa-whatsapp', c: 'linear-gradient(135deg,#25d366,#128c7e)', roi: '280%', leads: 274, pct: 64 },
      { n: 'Telegram', ic: 'fa-brands fa-telegram', c: 'linear-gradient(135deg,#2aabee,#1e88e5)', roi: '210%', leads: 221, pct: 52 },
      { n: 'SMS', ic: 'fa-comment-sms', c: 'linear-gradient(135deg,#f59e0b,#ef4444)', roi: '160%', leads: 152, pct: 40 },
    ],
    aiInsight: 'Автоматизация ROI за Q1–Q3: В январе–сентябре 2025 года ROI вырос на 22%. Основные драйверы: Email-рассылки (+15%), Рекламные кампании (+8%). Рекомендация: увеличить бюджет на Email до 40%.',
    leadDynamics: {
      months: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен'],
      series: [
        { name: 'Реклама', c: '#6366f1', data: [120, 135, 150, 180, 210, 240, 260, 290, 310] },
        { name: 'Email', c: '#ec4899', data: [80, 90, 95, 110, 130, 150, 160, 175, 190] },
        { name: 'Соцсети', c: '#f59e0b', data: [50, 55, 60, 70, 80, 90, 100, 110, 120] },
        { name: 'Сайт', c: '#34d399', data: [30, 35, 40, 45, 50, 55, 60, 65, 70] },
      ],
    },
    leadDistribution: [
      { n: 'Реклама', v: 38, c: '#6366f1' },
      { n: 'Email', v: 27, c: '#ec4899' },
      { n: 'Соцсети', v: 20, c: '#f59e0b' },
      { n: 'Сайт', v: 15, c: '#34d399' },
    ],
    teamActivity: [
      { who: 'Ольга Зайцева', av: 'ОЗ', avc: 'linear-gradient(135deg,#8b5cf6,#ec4899)', action: 'Запустила кампанию', target: '«Чёрная пятница»', time: '2 ч. назад' },
      { who: 'Дмитрий Орлов', av: 'ДО', avc: 'linear-gradient(135deg,#6366f1,#a855f7)', action: 'Обновил сегмент', target: '«Спящие VIP»', time: '4 ч. назад' },
      { who: 'Анна Ковалёва', av: 'АК', avc: 'linear-gradient(135deg,#f59e0b,#ef4444)', action: 'Настроила A/B-тест', target: 'Email-рассылка', time: 'Вчера' },
    ],
  },

  hr: {
    candidates: [
      { n: 'Мария Соколова', r: 'Middle Python', av: 'МС', avc: 'linear-gradient(135deg,#ec4899,#a855f7)', score: 74, sc: 'rgba(245,158,11,.35);color:#fbbf24', src: 'hh.ru', tags: [['Python', 'rgba(99,102,241,.35)', '#a5b4fc']] },
      { n: 'Дмитрий Волков', r: 'Junior Backend', av: 'ДВ', avc: 'linear-gradient(135deg,#6366f1,#3b82f6)', score: 61, sc: 'rgba(99,102,241,.35);color:#818cf8', src: 'Карьерный сайт', tags: [['Django', 'rgba(52,211,153,.35)', '#34d399']] },
      { n: 'Ольга Новикова', r: 'Senior Python', av: 'ОН', avc: 'linear-gradient(135deg,#8b5cf6,#a855f7)', score: 88, sc: 'rgba(52,211,153,.35);color:#34d399', src: 'LinkedIn', tags: [['Python', 'rgba(99,102,241,.35)', '#a5b4fc'], ['ML', 'rgba(236,72,153,.35)', '#f9a8d4']] },
      { n: 'Екатерина Морозова', r: 'Senior Python', av: 'ЕМ', avc: 'linear-gradient(135deg,#10b981,#059669)', score: 91, sc: 'rgba(52,211,153,.35);color:#34d399', src: 'Referral', tags: [['Python', 'rgba(99,102,241,.35)', '#a5b4fc'], ['K8s', 'rgba(52,211,153,.35)', '#34d399']] },
      { n: 'Алексей Иванов', r: 'Senior Python', av: 'АИ', avc: 'linear-gradient(135deg,#6366f1,#a855f7)', score: 96, sc: 'rgba(52,211,153,.35);color:#34d399', src: 'hh.ru', tags: [['Python', 'rgba(99,102,241,.35)', '#a5b4fc'], ['Топ-кандидат', 'rgba(52,211,153,.35)', '#34d399']] },
      { n: 'Сергей Кузнецов', r: 'Senior Python', av: 'СК', avc: 'linear-gradient(135deg,#a855f7,#ec4899)', score: 93, sc: 'rgba(52,211,153,.35);color:#34d399', src: 'LinkedIn', tags: [['ждёт ответа', 'rgba(245,158,11,.35)', '#fbbf24']] },
    ],
    hireCols: [
      { name: 'Новые отклики', ic: 'fa-inbox', c: '#818cf8', idx: [0, 1] },
      { name: 'Скрининг', ic: 'fa-magnifying-glass', c: '#a855f7', idx: [2] },
      { name: 'Интервью HR', ic: 'fa-comments', c: '#f472b6', idx: [3] },
      { name: 'Интервью с рук.', ic: 'fa-user-tie', c: '#fbbf24', idx: [4] },
      { name: 'Оффер', ic: 'fa-file-signature', c: '#34d399', idx: [5] },
    ],
    vacancies: [
      { n: 'Senior Python Developer', ic: 'fa-code', c: 'linear-gradient(135deg,#6366f1,#a855f7)', dep: 'Разработка', loc: 'Москва · гибрид', cand: 32, due: 'до 30.07', prog: 75, st: 'Горит', stc: 'background:rgba(239,68,68,.35);color:#f87171' },
      { n: 'Менеджер по продажам', ic: 'fa-handshake', c: 'linear-gradient(135deg,#f59e0b,#ef4444)', dep: 'Продажи', loc: 'Удалённо', cand: 48, due: 'до 12.08', prog: 45, st: 'Открыта', stc: 'background:rgba(52,211,153,.35);color:#34d399' },
      { n: 'UX/UI Дизайнер', ic: 'fa-pen-ruler', c: 'linear-gradient(135deg,#ec4899,#f472b6)', dep: 'Продукт', loc: 'СПб · офис', cand: 27, due: 'до 20.08', prog: 60, st: 'Открыта', stc: 'background:rgba(52,211,153,.35);color:#34d399' },
      { n: 'Специалист поддержки', ic: 'fa-headset', c: 'linear-gradient(135deg,#10b981,#059669)', dep: 'Поддержка', loc: 'Удалённо', cand: 64, due: 'до 05.08', prog: 30, st: 'Массовый набор', stc: 'background:rgba(99,102,241,.35);color:#818cf8' },
    ],
    onboarding: [
      { n: 'Дмитрий Волков', role: 'Junior Backend', av: 'ДВ', c: 'linear-gradient(135deg,#6366f1,#3b82f6)', mentor: 'Дмитрий Орлов', day: 'День 5 / 90', stc: 'background:rgba(245,158,11,.35);color:#fbbf24',
        steps: [{ l: 'Оффер', d: 1 }, { l: 'Документы', d: 1 }, { l: 'Доступы', cur: 1 }, { l: 'Welcome', cur: 0 }, { l: 'Обучение', cur: 0 }, { l: 'Аттестация', cur: 0 }] },
    ],
    ipr: [
      { n: 'Дмитрий Орлов', role: 'Менеджер', goal: 'Руководитель', av: 'ДО', c: 'linear-gradient(135deg,#6366f1,#a855f7)', skills: [['Продажи', 85, '#34d399'], ['Менторинг', 60, '#f59e0b'], ['Стратегия', 40, '#f87171']] },
      { n: 'Ольга Зайцева', role: 'Маркетинг', goal: 'Head of Marketing', av: 'ОЗ', c: 'linear-gradient(135deg,#8b5cf6,#ec4899)', skills: [['Performance', 78, '#34d399'], ['Стратегия', 52, '#f59e0b'], ['Управление', 35, '#f87171']] },
    ],
  },

  messenger: {
    chats: [
      { id: 0, name: 'Мария Карнаух', av: 'МК', c: 'linear-gradient(135deg,#6b7280,#4b5563)', time: 'Вт', prev: 'Я с вами в команде!', unread: 0, sub: 'В сети',
        msgs: [
          { t: 'Привет! Рада присоединиться к команде!', w: 'Мария Карнаух', out: false, tm: '10:20' },
          { t: 'Добро пожаловать, Мария! Если будут вопросы — пиши.', out: true, tm: '10:22' },
          { t: 'Спасибо! Я с вами в команде!', w: 'Мария Карнаух', out: false, tm: '10:38' },
        ] },
      { id: 1, name: 'Общий чат', av: '', ic: 'fa-comments', c: 'linear-gradient(135deg,#6366f1,#a855f7)', time: 'Вт', prev: 'Приглашение отправлено.', unread: 0, sub: '27 участников',
        msgs: [
          { date: 'Среда, 20 мая' },
          { sys: 'Марат Нуруллин отправил приглашение Марат Байбакову.', tm: '17:50' },
          { sys: 'Марат Нуруллин отправил приглашение Алексу Трофимову.', tm: '17:52' },
          { sys: 'Марат Нуруллин отправил приглашение Ирине Тарантиновой.', tm: '17:53' },
          { date: 'Пятница, 22 мая' },
          { sys: 'Марат Нуруллин отправил приглашение Даулету Шарафетдинову.', tm: '15:15' },
          { date: 'Среда, 27 мая' },
          { sys: 'Марат Нуруллин добавил права администратора для Светослава Яшкина.', tm: '11:06' },
          { date: 'Сегодня' },
          { t: 'Коллеги, обновлён график задач.', out: true, tm: '09:30' },
          { t: 'Принято, спасибо!', w: 'Дмитрий Орлов', out: false, tm: '09:45', replyTo: 9 },
        ] },
      { id: 2, name: 'Компания: Ромашка ООО', av: '', ic: 'fa-building', c: 'linear-gradient(135deg,#34d399,#10b981)', time: '23 июн', prev: 'Обсудить условия оплаты', unread: 1, sub: '5 участников',
        msgs: [
          { t: 'Отправили КП на согласование.', out: true, tm: '14:00' },
          { t: 'Спасибо! Обсудим на следующей неделе.', w: 'Игорь Смирнов', out: false, tm: '15:30' },
        ] },
      { id: 3, name: 'Компания: ГринЛайт', av: '', ic: 'fa-building', c: 'linear-gradient(135deg,#a855f7,#ec4899)', time: '22 июн', prev: 'Договор подписан', unread: 0, sub: '4 участника',
        msgs: [
          { t: 'Договор подписан. Начинаем внедрение.', out: true, tm: '11:00' },
          { t: 'Отлично! Назначьте дедлайн.', w: 'Олег Кузнецов', out: false, tm: '11:20' },
        ] },
      { id: 4, name: 'Игорь Новиков', av: 'ИН', c: 'linear-gradient(135deg,#8b5cf6,#ec4899)', time: '14 июн', prev: 'Не беспокоить', unread: 0, sub: 'Не в сети',
        msgs: [
          { t: 'Нужна помощь с отчётом по рекламе.', w: 'Игорь Новиков', out: false, tm: '16:00' },
        ] },
      { id: 5, name: 'Компания: ПМТ 96, ООО', av: '', ic: 'fa-building', c: 'linear-gradient(135deg,#8b5cf6,#6366f1)', time: '10 июн', prev: 'К чату присоединились общие компании', unread: 0, sub: '23 участника',
        msgs: [
          { sys: 'К чату присоединились общие компании.', tm: '12:08' },
          { t: 'Проверьте карточку сделки перед встречей.', out: true, tm: '12:12' },
        ] },
      { id: 6, name: 'Компания: ЭОС ЭСК', av: '', ic: 'fa-building', c: 'linear-gradient(135deg,#db2777,#a855f7)', time: '28 мая', prev: 'К чату присоединился Павел Лазар...', unread: 0, sub: '12 участников',
        msgs: [
          { sys: 'К чату присоединился Павел Лазарев.', tm: '10:22' },
          { t: 'Добро пожаловать в рабочую группу.', out: true, tm: '10:24' },
        ] },
      { id: 7, name: 'Ирина Тарантинова', av: 'ИТ', c: 'linear-gradient(135deg,#0ea5e9,#3b82f6)', time: '23 июн', prev: 'Я с вами в команде!', unread: 0, sub: 'В сети',
        msgs: [
          { t: 'Я с вами в команде!', w: 'Ирина Тарантинова', out: false, tm: '10:38' },
        ] },
      { id: 8, name: 'Нецелевые компании', av: 'НК', c: 'linear-gradient(135deg,#f59e0b,#ef4444)', time: '14 июн', prev: 'Пользователь', unread: 0, sub: 'Группа',
        msgs: [
          { sys: 'Михаил Серко зарегистрировал нецелевые компании.', tm: '16:13' },
        ] },
    ],
  },
};
